<?php 
$lan = array(
  "NoRecord" => "Ingen sådan post",
  "BackToBList" => "Tillbaka till listan över avvisade utskick",
  "NotFound" => "Ej funnen<br/>",
  "AddedToB" => "Lade till %s till antalet avvisade utskick för medlemmen %s<br/>",
  "NotAddedToB" => "Kunde inte lägga till %s till antalet avvisade utskick för medlemmen %s<br/>",
  "MadeUnconfirmed" => "Gjorde medlemmen %s obekräftad<br/>",
  "MadeUserRText" => "Gjorde medlemmen %s till textmottagare<br/>",
  "DelUser" => "Tog bort medlemmen %s<br/>",
  "DeletingB" => "Tar bort avvisat utskick %s ..\n",
  "DoneAndLoading" => "..Färdig, laddar nästa avvisade utskick..",
  "NoSRecord" => "Ingen sådan post",
  "PossibleActions" => "Möjliga handlingar:",
  "ForUser" => "För medlemmar med e-postadress",
  "IncreaseB" => "Öka antalet avvisade utskick med",
  "IncreaseBNote" => "(använd negativa antal för att minska)",
  "MarkAsUnconfirmed" => "Markera medlemmen som obekräftad",
  "MarkAsUnconfirmedNote" => "(så att du kan återsända bekräftelsemeddelandet)",
  "SetReceiveText" => "Sätt medlemmen som textmottagare istället för HTML-mottagare",
  "DelUser1" => "Ta bort medlem",
  "DelAndGo" => "Ta bort det här avvisade utskicket och gå till nästa",
  "DoAbove" => "Gör ovanstående",
  "BounceDetails" => "Detaljer för avvisat utskick:",
  "ID" => "ID",
  "Date" => "Datum",
  "Status" => "Status",
  "Comment" => "Kommentar",
  "Header" => "Utskickshuvud",
  "Body" => "Utskickskropp",
  
  # new in 2.9.5
  'Regular Expression' => 'Regular Expression',
  'Action' => 'Handling',
  'Memo for this rule' => 'Anteckning för denna regel',
  'Add new Rule' => 'Lägg till regel',
  'Create New Rule based on this bounce' => 'Skapa ny regel baserad på detta avvisade utskick',
);
?>
