<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Din databas är föråldrad, vänligen uppgradera den',
  'Your version' => 'Din version',
  'Latest version' => 'Senaste versionen',
  'phplist version' => '<a href="http://www.phplist.com">phplist</a>-version',
  'Database has not been initialised' => 'Databasen har inte initialiserats',
  'go to' => 'gå till',
  'Initialise Database' => 'Initialisera databas',
  'to continue' => 'för att fortsätta',
  'A new version of PHPlist is available!' => 'En ny PHPlist-version är tillgänglig!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'Den nya versionen kan ha åtgärdade säkerhetsproblem<br/>så du rekommenderas uppgradera så fort som möjligt',
  'View what has changed' => 'Se vad som har förändrats',
  'Download' => 'Ladda ner',
  'System Functions' => 'Systemfunktioner',
  'Setup ' => 'Ställ in ',
  'Check Database structure' => 'Kolla databasstrukturen',
  'View the eventlog' => 'Visa händelseloggen',
  'Configuration functions' => 'Konfigurationsfunktioner',
  'Configure Attributes' => 'Konfigurera attribut',
  'Control values for' => 'Kontrollera värden för',
  'Control values for' => 'Kontrollera värden för',
  'Control values for' => 'Kontrollera värden för',
  'Configure Subscribe pages' => 'Konfigurera anmälningssidor',
  'List and user functions' => 'Liste- och medlemsfunktioner',
  'List the current lists' => 'Lista befintliga listor',
  'List all Users' => 'Lista alla medlemmar',
  'Reconcile the user database' => 'Få medlemsdatabasen att stämma',
  'Import Users' => 'Importera medlemmar',
  'Export Users' => 'Exportera medlemmar',
  'Administrator functions' => 'Administratörsfunktioner',
  'Add, edit and remove Administrators' => 'Lägg till, redigera och ta bort administratörer',
  'Configure attributes for administrators' => 'Konfigurera attribut för administratörer',
  'Message functions' => 'Meddelandefunktioner',
  'Configure Templates' => 'Konfigurera mallar',
  'List all Messages' => 'Lista alla utskick',
  'Process the Message queue' => 'Bearbeta utskickskön',
  'RSS Functions' => 'RSS-funktioner',
  'Get RSS feeds' => 'Hämta RSS-feeds',
  'View RSS items' => 'Se RSS-poster',
  'Plugins' => 'Insticksmoduler',
  'Upgrade' => 'Uppgradera',
'Change your details (e.g. password)' => 'Ändra dina detaljer (t. ex. lösenord)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Du har ställt in TEST i config.php till 1, så endast vad som skulle ha sänts kommer visas',

  # added at a later stage
  'setup' => 'ställ in',
  'upgrade' => 'uppgradera',
  'dbcheck' => 'databaskoll',
  'eventlog' => 'händelselogg',
  'attributes' => 'attribut',
  'spage' => 'anmälningssida',
  'list' => 'lista',
  'reconcileusers' => 'stäm av medlemmar',
  'import' => 'import',
  'export' => 'export',
  'admins' => 'administratörer',
  'adminattributes' => 'administratörsattribut',
  'send' => 'sänd',
  'templates' => 'mallar',
  'processqueue' => 'processkö',
  'processbounces' => 'bearbeta avvisade',
  'getrss' => 'hämta rss',
  'viewrss' => 'visa rss',
  'admin' => 'admin',
  'preparesend' => 'förbered sänd',
  'sendprepared' => 'sänd förberedda',


);

?>
