<?php 
$lan = array(

  'add_list' => 'Lägg till en lista', //duplicated in import1_text
  'cannot connect to remote database' => 'kan inte ansluta till extern databas',
  'No users to copy, is the prefix correct?' => 'Inga medlemmar att kopiera, är prefixet korrekt?',
  'Please enter details of the remote Server' => 'Vänligen ange detaljer för den externa servern',
  'Server:' => 'Server:',
  'user' => 'Medlem:',
  'Password:' => 'Lösenord:',
  'Database Name:' => 'Databasnamn:',
  'Table prefix:' => 'Tabellprefix:',
  'Usertable prefix:' => 'Medlemstabellprefix:',
  'select_lists' => 'Välj listorna som e-postadresserna ska läggas till i',
  'Copy lists from remote server (lists are matched by name)' => 'Kopiera listor från extern server (listor matchas genom namn)',
  'Mark new users as HTML:' => 'Markera nya medlemmar som HTML-mottagare:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'Om du kryssar för "Skriv över befintliga"  kommer information om en medlem i databasen skrivas över med den importerade informationen. Medlemmar matchas genom dess e-postadresser.',
  'Overwrite Existing:' => 'Skriv över befintliga:',
  'Making connection with remote database' => 'Ansluter till extern databas',
  'Getting data from ' => 'Hämtar data från ',
  'Remote version is' => 'Extern version är',
  'Remote version has' => 'Extern version har',
  'users' => 'medlemmar',
  'lists' => 'listor',
  'Copying lists' => 'Kopierar listor',
  'list' => 'Lista',
  'exists locally' => 'finns lokalt',
  'created locally' => 'skapades lokalt',
  'Remote list' => 'Extern lista',
  'not created' => 'skapades inte',
  'Copying attributes' => 'Kopierar attribut',
  'Attribute' => 'Attribut',
  'Copying users' => 'Kopierar medlemmar',
  'overwriting local data' => 'skriver över lokal data',
  'keeping local data' => 'behåller lokal data',
  'is a new user' => 'är en ny medlem',
  'Error, no mapped attribute for' => 'Fel, inga länkade attribut för',
  'Error, no local list defined for' => 'Fel, ingen lokal lista definierad för',
  'No lists available' => 'Inga listor finns tillgängliga',
  'Done' => 'Färdig',
  'new users' => 'nya medlemmar',
  'and' => 'och',
  'existing users' => 'befintliga medlemmar',
  'continue' => 'Fortsätt',

);
?>
