<?php
$lan = array(
  "Import emails from IMAP folders" => "Importera e-postadresser från IMAP-mappar",
  "No lists available" => "Inga listor finns tillgängliga",
  "Add a list" => "Lägg till en lista",
  "personal" => "personligt",
  "email" => "e-postadress",
  "folder" => "mapp",
  "date" => "datum",
  "can't connect" => "kan inte ansluta",
  "Processing" => "Bearbetar",
  "messages" => "meddelanden",
  "done" => "färdig",
  "imap_getmailboxes failed" => "imap_getmailboxes misslyckades",
  "Please enter details of the IMAP account" => "Vänligen ange detaljer för IMAP-kontot",
  "Select the headers fields to search" => "Välj huvudfälten som ska sökas genom",
  "Select the lists to add the emails to" => "Välj listorna som e-postadresserna ska läggas till i",
  "Adding users to list" => "Lägger till medlem i lista",
  "Mark new users as HTML" => "Markera nya medlemmar som HTML-mottagare",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "Om du kryssar för",
  "Overwrite Existing" => "Skriv över befintliga",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "kommer information om en medlem i databasen ersättas av den importerade informationen. Medlemmar matchas genom deras e-postadresser.",
  "Only use complete addresses" => "Använd endast fullständiga adresser",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "kommer adresser som inte har riktiga namn ignoreras. Annars kommer alla e-postadresser importeras.",
  "If you choose" => "Om du väljer",
  "send notification email" => "sänd notifieringsmeddelande",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "kommer medlemmarna som du lägger till skickas en bekräftelseförfrågan för anmälan som de måste svara på. Detta rekommenderas då det identifierar ogiltiga e-postadresser.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "Sänd&nbsp;notifierings-&nbsp;meddelande&nbsp;",
  "Make confirmed immediately" => "Bekräfta omedelbart",
  "import3info" => "Det finns två sätt att lägga till medlemmarnas namn,
 antingen med ett attribut för hela namnet eller två attribut, ett för förnamnet och ett för efternamnet.
Om du använder 'två attribut' kommer namnet delas efter det första mellanslagstecknet.",
  "Use one attribute for name" => "Använd ett attribut för namn",
  'Use two attributes for the name' => 'Använd två attribut för namn',
  "Attribute one" => "Attribut ett",
  "Create Attribute" => "Skapa attribut",
  "Attribute two" => "Attribut två",
  "Cannot continue" => "Kan inte fortsätta",
  "ok" => "ok",
  "failed" => "misslyckades",
  "Processed" => "Bearbetade",
  "folders and" => "mappar och",
  "unique emails found" => "unika e-postadresser hittades",
  "list" => "lista",
  "lists" => "listor",
  "new email was" => "ny e-postadress blev",
  "new emails were" => "nya e-postadresser blev",
  "email was" => "e-postadress blev",
  "emails were" => "e-postadresser blev",
  "All the emails already exist in the database and are members of the" => "Alla e-postadresser fanns redan i databasen och är medlemmar i",
  "succesfully imported to the database and added to" => "importerades till databasen och lades till i",
  "subscribed to the" => "anmäldes till",
  "emails already existed in the database" => "e-postadresser fanns redan i databasen",
  "Invalid Emails found." => "Ogiltiga e-postadresser hittades.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "Dessa poster lades till men e-postadressen har hittats på. Du kan hitta dem genom att söka efter",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "Dessa poster togs bort. Kolla din källkod och återimportera datan. Dubbletter kommer identifieras.",
  "No emails found" => "Inga e-postadresser hittades",
  "Import some more emails" => "Importera några fler e-postadresser",
  'Server' => 'Server',
  'User' => 'Medlem',
  'Password' => 'Lösenord',
  'Continue' => 'Fortsätt',
  'Process Selected Folders' => 'Bearbeta valda mappar',
);
?>
