<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Du har inte tillräckliga privilegier för att se den här sidan',
  'Add a user' => 'Lägg till en medlem (ange e-postadress)',
  'add user' => 'Lägg till medlem',
  'Members of' => 'Medlemmar i',
  'Tag all users in this page' => 'Kryssa för alla medlemmar på den här sidan',
  'back to this list' => 'tillbaks till listredigeringen',
  'Download users on this list as a CSV file' => 'Ladda ner medlemmarna på den här listan som en CSV-fil',
  'Please enter a listid' => 'Vänligen ange ett list-ID',
  'Processing' => 'Bearbetar',
  'users were moved to' => 'medlemmar flyttades till',
  'users were copied to' => 'medlemmar kopierades till',
  'users were deleted from this list' => 'medlemmar togs bort från den här listan',
  'Users found, click add to add this user' => 'medlemmar hittades, klicka på &quot;Lägg till&quot; för att lägga till den här medlemmen',
  'Add' => 'Lägg till',
  'No user found with that email' => 'Ingen medlem hittades med den e-postadressen',
  'Inserting user' => 'Infogar medlem',
  'User added' => 'Medlem lades till',
  'Deleting' => 'Tar bort',
  'Done' => 'Färdig',
  'Users on this list' => 'medlemmar är med på den här listan',
  'Listing user' => 'Listar medlemmar',
  'to' => 'till',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Listar medlem 1 till 50',
  'Members' => 'Medlemmar',
  'confirmed' => 'bekräftade',
  'tag' => 'välj',
  'del' => 'ta bort',
  'Delete'=>'Ta bort',
  '# msgs' => '# utskick',
  '# rss' => '# rss',
  'rss freq' => 'rss-frekv',
  'last sent' => 'senast sänt',
  'What to do with "Tagged" users' => 'Att göra med förkryssade medlemmar',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Detta gör att endast medlemmar på den här sidan som är förkryssade kommer påverkas',
  'delete' => 'Ta bort',
  'Move' => 'Flytta',
  'Copy' => 'Kopiera',
  'Nothing' => 'Ingenting',
  'to' => 'till', # as in destination
  'from this list' => 'från den här listan',
  'What to do with all users' => 'Att göra med alla medlemmar',
  'This will process all users on this list' => 'Detta gör att alla medlemmar på den här listan kommer påverkas',
  'do it' => 'gör det',
  
  
);
?>
