<?php
$lan = array(
 'Please select a message to display' => 'Vänligen välj ett meddelande att visa',
 'Attachments for this message' => 'Bifogade filer för det här utskicket',
 'No attachments' => 'Inga bifogade filer',
 'Filename' => 'Filnamn',
 'Size' => 'Storlek',
 'Mime Type' => 'Mime-typ',
 'Description' => 'Beskrivning',
 'Lists this message has been sent to' => 'Listor som det här utskicket har sänts till',
 'None yet' => 'Inga än',
 'Send this (same) message to (a) new list(s)' => 'Sänd det här utskicket till andra listor',
 'List is Active' => 'Listan är aktiv',
 'List is not Active' => 'Listan är inaktiv',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Obs:</b> det här utskicket har redan sänts till alla listor. För att återsända det till nya medlemmar, använd "Ställ i kö på nytt"-funktionen.',
 'Resend' => 'Sänd',
 'id' => 'id',
 'subject' => 'ämne',
 'from field' => 'från-fält',
 'to field' => 'till-fält',
 'reply to' => 'svara till',
 'message' => 'meddelande',
 'textmessage' => 'textmeddelande',
 'footer' => 'meddelandefot',
 'entered' => 'angiven',
 'modified' => 'modifierad',
 'embargo' => 'embargo',
 'repearinterval' => 'upprepningsintervall',
 'repeatuntil' => 'upprepatills',
 'status' => 'status',
 'userselection' => 'medlemsval',
 'sent' => 'sänt',
 'htmlformatted' => 'htmlformaterat',
 'sendformat' => 'sändningsformat',
 'template' => 'mall',
 'processed' => 'bearbetat',
 'as text' => 'som text',
 'as html' => 'som html',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'as pdf' => 'som pdf',
 'as text and pdf' => 'som text och pdf',
 'viewed' => 'visad',
 'bounce count' => 'antal avvisade utskick',
 'send start' => 'sändningsstart',
 'RSS template' => 'RSS-mall',
 'owner' => 'ägare',

 # new in 2.10.1
 'edit this message' => 'Redigera det här meddelandet',
);
?>
