<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'Körs i testläge, inga utskick kommer sändas. Kolla din config-fil.',
'The following restrictions have been set by your ISP:' => 'Följande begränsningar har satts upp av din Internetleverantör:',
'Script stage' => 'Skriptstadium',
'Finished, Nothing to do' => 'Färdig, ingenting att göra',
'messages sent in' => 'utskick sända på',
'seconds' => 'sekunder',
'invalid emails' => 'ogiltiga e-postadresser',
'emails failed (will retry later)' => 'utskick misslyckades (kommer försöka igen senare)',
'emails unconfirmed (not sent)' => 'utskick obekräftade (ej sända)',
'Warning: script never reached stage 5' => 'Varning: skriptet nådde aldrig stadium 5',
'This may be caused by a too slow or too busy server' => 'Det här kan ha orsakats av en för långsam eller upptagen server',


'In safe mode, batches are set to a maximum of 100' => 'I safe mode sätts partistorleken till högst 100',
'Running in safe mode' => 'Körs i safe mode',
'msgs/hr' => 'utskick/timme',
'Reload required' => 'Omstart krävs',
'Finished, All done' => 'Färdig. Allt klart',
'Script finished, but not all messages have been sent yet.' => 'Skriptet färdigt, men alla utskick har inte sänts än.',
'Finished this run' => 'Den här körningen har färdigställts',
'(test)' => '(test)',
'Would have sent' => 'Skulle ha sänts',
'(test)' => '(test)',
'Would have sent' => 'Skulle ha sänts',
'Started' => 'Började',
'Processing has been suspended by your ISP, please try again later' => 'Bearbetningen har avbrutits av din Internetleverantör. Vänligen försök igen senare',
'Sending in batches of' => 'Sänds i partier om',
'emails' => 'utskick',
'This batch will be' => 'Det här partiet kommer bestå av',
'emails, because in the last' => 'e-postadresser, eftersom i det senaste blev',
'emails were sent' => 'utskick skickade',
'Sending in batches of' => 'Sänds i partier om',
'emails' => 'utskick',
'In the last' => 'I de senaste',
'seconds more emails were sent' => 'sekunderna sändes fler utskick',
'than is currently allowed per batch' => 'än vad som för närvarande är tillåtet per parti',
'Sent in last run' => 'Sändes i den sista körningen',
'Skipped in last run' => 'Hoppades över i den sista körningen',
'Processing has started,' => 'Bearbetning har börjat,',
'message(s) to process.' => 'utskick att bearbeta.',
'It is safe to click your stop button now, report will be sent by email to' => 'Du kan utan fara klicka på "stopp"-knappen nu. En rapport kommer i så fall sändas via e-post till',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Din webbserver körs i "safe_mode". Vänligen håll detta fönster öppet. Det kan uppdateras flera gånger för att försäkra sig om att alla utskick har sänts.',
'Reports will be sent by email to' => 'Rapporter kommer sändas via e-post till',
'Processing message' => 'Bearbetar utskick',
'Message' => 'Utskick',
'is an RSS feed for' => 'är en RSS-feed för',
'Looking for users' => 'Kollar efter medlemmar',
'users apply for attributes, now checking lists' => 'medlemmar uppfyller attributen, kolla nu listor',
'No users apply for attributes' => 'Inga medlemmar uppfyller attributen',
'looking for users who can be excluded from this mailing' => 'kollar efter medlemmar som kan uteslutas från denna processkö-körning',
'Process Killed by other process' => 'Processen dödades av en annan process',
'Found them' => 'Hittade',
'to process' => 'att bearbeta',
'No users to process for this batch' => 'Inga medlemmar att bearbeta i det här partiet',
'batch limit reached' => 'partigräns nådd',
'Process Killed by other process' => 'Processen dödades av en annan process',
'Message I was working on has disappeared' => 'Utskicket som jag arbetade på har försvunnit',
'Sending' => 'Sänds',
'It took' => 'Det tog',
'seconds to send' => 'sekunder att sända',
'Failed sending to' => 'Misslyckades att sända till',
'Unconfirmed user' => 'Obekräftad medlem',
'Not sending to' => 'Sänder inte till',
'already sent' => 'har redan sänts',
'Processed' => 'Bearbetade',
'out of' => 'av',
'Hmmm, No users found to send to' => 'Hmmm, inga medlemmar att sända till hittade',
'It took' => 'Det tog',
'to send this message' => 'att sända det här utskicket',
'waiting for' => 'väntar på',
'to make sure we don\'t exceed our limit of' => 'för att säkerställa att vi inte överskriver vår gräns på',
'messages in' => 'utskick på',

### new in 2.9.5
'Message Sending has started' => 'Utskickssändning har påbörjats',
'phplist has started sending the message with subject %s' => 'phplist har börjat sända utskicket med ämne %s',
'to view the progress of this message, go to %s' => 'för att se framåtskridandet för detta utskick, gå till %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'Det har gjorts mer än 10 försök att sända till %s som har blockerats på grund av domänkvävning.',
'Introducing extra delay to decrease throttle failures' => 'Introducerar extra fördröjning för att minska kvävningsfel',
'%s is currently over throttle limit of %d per %d seconds' => '%s är för närvarande över kvävningsgränsen på %d per %d sekunder',
'not sending to ' => 'sänder inte till ',
'Message Sending has finished' => 'Utskickssändning har avslutats',
'phplist has finished sending the message with subject %s' => 'phplist har avslutat sändningen av utskicket med ämne %s',

'Sending of this message has been suspended' => 'Sändningen av detta utskick har avbrutits',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'Mindre än partistorleken sändes, så omstart sker inom kort',
'Waiting for %d seconds before reloading' => 'Väntar i %d sekunder innan omstart',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Vänligen låt det här fönstret vara öppnet. Du har aktiverat partibearbetning, så det kommer uppdateras flera gånger för att sända utskicken. Rapporter kommer sändas via e-post till',

);

?>
