<?php
$lan = array(

  'add_list' => 'Ajouter une liste', //duplicated in import1_text
  'cannot connect to remote database' => 'la connexion &agrave; la base du serveur distant a &eacute;chou&eacute;',
  'No users to copy, is the prefix correct?' => 'Il n&rsquo;y a pas d&rsquo;utilisateur &agrave; copier, le pr&eacute;fixe est-il correct?',
  'Please enter details of the remote Server' => 'Rentrez les coordonn&eacute;es du Serveur distant',
  'Server:' => 'Serveur:',
  'user' => 'Utilisateur:',
  'Password:' => 'Mot de passe:',
  'Database Name:' => 'Nom de la base de donn&eacute;es:',
  'Table prefix:' => 'Pr&eacute;fixe de la table:',
  'Usertable prefix:' => 'Pr&eacute;fix de la table des Utilisateurs (Usertable):',
  'select_lists' => 'S&eacute;lectionnez les listes auxquelles vous voulez ajouter les emails',
  'Copy lists from remote server (lists are matched by name)' => 'Copier les listes du serveur distant (les listes sont identifi&eacute;es par leur nom)',
  'Mark new users as HTML:' => 'Marquer les nouveaux utilisateurs comme devant recevoir les messages au format HTML:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'Si vous cochez "Ecraser Donn&eacute;es Existantes", l&rsquo;information sur un utilisateur dans la base de donn&eacute;es sera remplac&eacute;e par les donn&eacute;es import&eacute;es.  Les utilisateurs sont identifi&eacute;s par leur email.',
  'Overwrite Existing:' => 'Ecraser Donn&eacute;es Existantes:',
  'Making connection with remote database' => 'Connexion avec la base de donn&eacute;es distante',
  'Getting data from ' => 'R&eacute;cup&eacute;ration de donn&eacute;es de ',
  'Remote version is' => 'La version distante est',
  'Remote version has' => 'La version distante comporte',
  'users' => 'utilisateurs',
  'lists' => 'listes',
  'Copying lists' => 'Copie des listes',
  'list' => 'Liste',
  'exists locally' => 'existe en local',
  'created locally' => 'cr&eacute;&eacute; en local',
  'Remote list' => 'Liste distante',
  'not created' => 'non cr&eacute;&eacute;',
  'Copying attributes' => 'Copie des attributs',
  'Attribute' => 'Attribut',
  'Copying users' => 'Copie des utilisateurs',
  'overwriting local data' => '&eacute;crasement des donn&eacute;es en local',
  'keeping local data' => 'maintien des donn&eacute;es en local',
  'is a new user' => 'est un nouvel utilisateur',
  'Error, no mapped attribute for' => 'Erreur, aucun attribu d&eacute;fini pour',
  'Error, no local list defined for' => 'Erreur, aucune liste en local d&eacute;finie pour',
  'No lists available' => 'Aucune liste disponible',
  'Done' => 'C&rsquo;est fait',
  'new users' => 'nouveaux utilisateurs',
  'and' => 'et',
  'existing users' => 'utilisateurs d&eacute;j&agrave; existants',
  'continue' => 'Continuer',

);
?>