<?php 
$lan = array(
  "NoRecord" => "Nie ma takiego rekordu",
  "BackToBList" => "Powrót do listy zwrotów",
  "NotFound" => "Nie znaleziono<br/>",
  "AddedToB" => "Dodano %s do liczby zwrotów dla użytkownika %s<br/>",
  "NotAddedToB" => "Nie można dodać %s do liczby zwrotów dla użytkownika %s<br/>",
  "MadeUnconfirmed" => "Oznaczono użytkownika %s jako niepotwierdzony<br/>",
  "MadeUserRText" => "Użytkownikowi %s włączono odbieranie wiadomości tekstowych<br/>",
  "DelUser" => "Usunięto użytkownika %s<br/>",
  "DeletingB" => "Usuwam zwroty %s .. <br>",
  "DoneAndLoading" => "..Gotowe, ładuję następny zwrot..",
  "NoSRecord" => "Nie ma takiego rekordu",
  "PossibleActions" => "Możliwe działania:",
  "ForUser" => "Dla użytkownika o adresie e-mail",
  "IncreaseB" => "Zwiekszenie licznika zwrotów o",
  "IncreaseBNote" => "(użyj liczby ujemnej aby zmniejszyć)",
  "MarkAsUnconfirmed" => "Oznacz użytkownika jako nipotwierdzony",
  "MarkAsUnconfirmedNote" => "(a zatem możesz ponownie wysłać prośbę o potwiedzenie)",
  "SetReceiveText" => "Wysyłaj użytkownikowi wiadomości tekstowe zamiast HTML",
  "DelUser1" => "Usuń użytkownika",
  "DelAndGo" => "Usuń ten zwrot i przejdź do następnego",
  "DoAbove" => "Wykonaj powyższe",
  "BounceDetails" => "Detale zwrotu:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Status",
  "Comment" => "Komentarz",
  "Header" => "Nagłówek",
  "Body" => "Zawartość",
  
  # new in 2.9.5
  'Regular Expression' => 'Wyrażenie regularne',
  'Action' => 'Działanie',
  'Memo for this rule' => 'Notatka dla tej reguły',
  'Add new Rule' => 'Dodaj nową regułę',
  'Create New Rule based on this bounce' => 'Utwórz nową regułę na podstawie tego zwrotu',
);
?>