<?php
$lan = array( 
 'checklist for installation' => 'Lista kontrolna dla instalacji',
 'cannot be empty' => 'nie może byc puste',
 'Editing' => 'Edytuję',
 'save changes' => 'Zapisz zmiany',
 'edit' => 'edycja',

   # added 24 May 2006
  'delete user' => 'usuń użytkownika',
  'unconfirm user' => 'anuluj potwierdzenie',
  'blacklist user' => 'dodaj do czarnej listy',
  'delete user and bounce' => 'usuń użytkownika i odrzucenia',
  'unconfirm user and delete bounce' => 'anuluj potwierdzenie i usuń odrzucenia',
  'blacklist user and delete bounce' => 'dodaj do czarnej listy i usuń odrzucenia',
  'delete bounce' => 'usuń odrzucenia',
  'Website address (without http://)' => 'Adres strony (bez http://)',
  'Domain Name of your server (for email)' => 'Nazwa domeny Twojego serwera (dla email)',
  'Person in charge of this system (one email address)' => 'Osoba odpowiedzialna za ten system (jeden adres email)',
  'How often do you want to check for a new version of PHPlist (days)' => 'Jak często chcesz sprawdzać czy jest nowa wersja PHPlist (dni)',
  'List of people to CC in system emails (separate by commas)' => 'Lista osób DW w systemie mailingowym (oddzielone przecinkami)',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'Kto otrzymuje raporty (adres emial, oddziel wile adresów przecinakmi)',
  'From email address for system messages' => 'Adres emial w polu OD dla wiadomości systemowych',
  'What name do system messages appear to come from' => 'Z jaką nazwą mają przychodzić wiadomości systemowe',
  'Reply-to email address for system messages' => 'Adres Reply-to dla wiadomości systemowych',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'jeśli jest widoczna tylko jedna  lista, czy powinna być ukryta na sronie i automatycznie
    rozesłać do zarejestrowanych użytkowników (0/1)',
  'width of a textline field (numerical)' => 'szerokość pola tekstowego (liczba)',
  'dimensions of a textarea field (rows,columns)' => 'wymiary pola obszaru tekstowego (wiersze,kolumny)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'Czy admin powinien otrzymywać kopie wiadomości rejestrujących, wyrejestrujących oraz aktualizacyjnych (0/1)',
  'The default subscribe page when there are multiple' => 'Domyślna strona rejestrowania (jeśli jest kilka)',
  'The default HTML template to use when sending a message' => 'Domyślny szablon HTML używany podczas rozsyłania wiadomości',
  'URL where users can subscribe' => 'URL gdzie użytkownicy mogą się rejestrować',
  'URL where users can unsubscribe' => 'URL gdzie użytkownicy mogą się wyrejestrować',
  'URL where users have to confirm their subscription' => 'URL gdzie użytkownicy muszą potwierdzić swoją rejestrację',
  'URL where users can update their details' => 'URL gdzie użytkownicy mogą aktualizować swoje dane',
  'URL where messages can be forwarded' => 'URL gdzie wiadomości mogą być przekazywane',
  'Subject of the message users receive when they subscribe' => 'Temat wiadomości, którą otrzymują użytkownicy gdy sie rejestrują',
  'Message users receive when they subscribe' => 'Wiadomość, którą otrzymują użytkownicy gdy się rejestrują',
  'Subject of the message users receive when they unsubscribe' => 'Temat wiadomości, którą otrzymują użytkownicy gdy sie wyrejestrowują',
  'Message users receive when they unsubscribe' => 'Wiadomość, którą otrzymują użytkownicy gdy się wyrejestrowują',
  'Subject of the message users receive after confirming their email address' => 'Temat wiadomości, którą otrzymują użytkownicy po potwierdzeniu rejestracji',
  'Message users receive after confirming their email address' => 'Wiadomość którą otrzymują użytkownicy po potwierdzeniu rejestracji',
  'Subject of the message users receive when they have changed their details' => 'Temat wiadomości, którą użytkowincy otrzymują gdy aktualizują swoje dane',
  'Message that is sent when users change their information' => 'Wiadomość, którą użytkowincy otrzymują gdy aktualizują swoje dane',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => 'Część wiadomości, która jest wysyłana na nowy adres email gdy użytkownicy uaktualniają swoje dane i gdy został zmieniony ich adres email',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => 'Część wiadomości, która jest wysyłana na stary adres email gdy użytkownicy uaktualniają swoje dane i gdy został zmieniony ich adres email',
  'Subject of message to send when users request their personal location' => 'Temat wiadomości wysyłanej do użytkowników gdy zażądają osobistej lokalizacji',
  'Message to send when they request their personal location' => 'Wiadomość wysyłana do użytkowników gdy zażądają osobistej lokalizacji',
  'Default footer for sending a message' => 'Domyslna stopka dla wysyłanych wiadomości',
  'Footer used when a message has been forwarded' => 'Stopka używana gdy wiadomość jest przesyłana',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'Nagłówek stron publicznych. Nagłówek powinien zaczynać się od &lt;/head&gt; . Możesz dodać elementy nagłówka, alen ie dodawaj tytułu ani innych podstawowych elementów nagłówka.',
  'Footer of public pages' => 'Stopka stron publicznych',
  'Charset for HTML messages' => 'Zestaw znaków dla stron HTML',
  'Charset for Text messages' => 'Zestaw znaków dla wiadomości tekstowych',
  'CSS for HTML messages without a template' => 'CSS dla wiadomości HTML bez szablonu',
  'Domains that only accept text emails, one per line' => 'Domeny, które akceptują tylko wiadomości tekstowe (jeden wpis w jednej linii)',
  'Minimum amount of items to send in an RSS feed' => 'Minimalna ilość elementów wysyłanych w kanale RSS',
  'Template for text item in RSS feeds' => 'Szablon dla elementów tekstowych kanału RSS',
  'Template for HTML item in RSS feeds' => 'Szablon dla elementów HTML kanału RSS',
  'Maximum amount of items to send in an RSS feed' => 'Maksymalna ilość elementów wysyłanych w kanale RSS',
  'Template for separator between feeds in RSS feeds (text)' => 'Szablon dla separatora w kanale RSS (text)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'Szablon dla separatora w kanale RSS (HTML)',
  'Width in px of FCKeditor Area' => 'Szerokość w pikselach obszaru edytora FCKeditor',
  'Height in px of FCKeditor Area' => 'Wysokość w pikselach obszaru edytora FCKeditor',
);
?>