<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Towja baza danych jest nieaktualna, uaktualnij ją do najnowszej wersji',
  'Your version' => 'Twoja wersja',
  'Latest version' => 'Najnowsza wersja',
  'phplist version' => 'Wersja <a href="http://www.phplist.com">phplist</a>',
  'Database has not been initialised' => 'Baza danych nie została zainicjowana',
  'go to' => 'idź do',
  'Initialise Database' => 'inicjuję bazę danych',
  'to continue' => 'aby kontynuować',
  'A new version of PHPlist is available!' => 'Nowa wersja PHPlist jest dostępna!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'Nowa wersja może poprawić kwestię bezpieczeństwa,<br/>więc zalecamy uaktualnić najszybciej jak to możliwe',
  'View what has changed' => 'Zobacz co zostało zmienione',
  'Download' => 'Pobierz',
  'System Functions' => 'Funkcje systemu',
  'Setup ' => 'Ustawienia ',
  'Check Database structure' => 'Sprawdź strukturę bazy danych',
  'View the eventlog' => 'Przeglądaj dziennik zdarzeń',
  'Configuration functions' => 'Funkcje konfiguracji',
  'Configure Attributes' => 'Ustawienia atrybutów',
  'Control values for' => 'Ustawienia wartości dla',
  'Control values for' => 'Ustawienia wartości dla',
  'Control values for' => 'Ustawienia wartości dla',
  'Configure Subscribe pages' => 'Ustawienia stron rejestracji',
  'List and user functions' => 'Funkcje list i użytkownika',
  'List the current lists' => 'Wyświetl obecne listy',
  'List all Users' => 'Wyświetl wszystkich użytkowników',
  'Reconcile the user database' => 'Operacje na bazach użytkowników',
  'Import Users' => 'Import użytkowników',
  'Export Users' => 'Eksport użytkowników',
  'Administrator functions' => 'Funkcje administratora',
  'Add, edit and remove Administrators' => 'Dodaj, edytuj i usuń Administratorów',
  'Configure attributes for administrators' => 'Konfiguruj atrybuty Administratorów',
  'Message functions' => 'Funkcje wiadomości',
  'Configure Templates' => 'Funkcje szablonów',
  'List all Messages' => 'Wyświetl wszystkie wiadomości',
  'Process the Message queue' => 'Przetwarzaj kolejkę wiadomości',
  'RSS Functions' => 'Funkcje kanałów RSS',
  'Get RSS feeds' => 'Pobierz kanały RSS',
  'View RSS items' => 'Wyświetla elementy RSS',
  'Plugins' => 'Dodatki',
  'Upgrade' => 'Upgrade',
'Change your details (e.g. password)' => 'Zmień swoje ustawienia (np. hasło)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Ustawiłeś TEST w config.php na 1, więc będzie tylko pokazane co zostałoby wysłane',

  # added at a later stage
  'setup' => 'ustawienia',
  'upgrade' => 'uaktualnij',
  'dbcheck' => 'baza',
  'eventlog' => 'dziennik zdarzeń',
  'attributes' => 'atrybuty',
  'spage' => 'strona rejestracji',
  'list' => 'listy',
  'reconcileusers' => 'uzgadnianie użytkowników',
  'import' => 'import',
  'export' => 'eksport',
  'admins' => 'administratorzy',
  'adminattributes' => 'atrybuty admina',
  'send' => 'wyślij',
  'templates' => 'szablony',
  'processqueue' => 'kolejka wiadomości',
  'processbounces' => 'kolejka zwrotów',
  'getrss' => 'pobierz rss',
  'viewrss' => 'zobacz rss',
  'admin' => 'admin',
  'preparesend' => 'przygotuj wysyłkę',
  'sendprepared' => 'wyślij przygotowane',


);

?>