<?php 
$lan = array(

  'add_list' => 'Dodaj listę', //duplicated in import1_text
  'cannot connect to remote database' => 'nie można połączyć się z bazą danych',
  'No users to copy, is the prefix correct?' => 'Brak użytkowników do skopiowania, czy przedrostek jest prawidowy?',
  'Please enter details of the remote Server' => 'Wprowadź detale zdalnego serwera',
  'Server:' => 'Serwer:',
  'user' => 'Użytkownik:',
  'Password:' => 'Hasło:',
  'Database Name:' => 'Nazwa bazy danych:',
  'Table prefix:' => 'Przedrostek tabeli:',
  'Usertable prefix:' => 'Przedrostek tabeli użytkownika:',
  'select_lists' => 'Wybierz listy aby dodać adresy',
  'Copy lists from remote server (lists are matched by name)' => 'Kopiuj listy ze zdalnego serwera (listy są dopasowywane po nazwie)',
  'Mark new users as HTML:' => 'Oznacz nowych użytk. jako HTML:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'Jeśli zaznaczysz "Nadpisz istniejące", informacje o użytkowniku w bazie danych zostaną zastąpione importowanymi informacjami. Użytkownicy są dopasowywani po adreseie email.',
  'Overwrite Existing:' => 'Nadpisz istniejące:',
  'Making connection with remote database' => 'Tworzenie połączenie ze zdalną bazą danych',
  'Getting data from ' => 'Pobieranie danych z ',
  'Remote version is' => 'Wersja zdalnej bazy',
  'Remote version has' => 'Zdalna baza ma',
  'users' => 'użytkowników',
  'lists' => 'list',
  'Copying lists' => 'Kopiowanie list',
  'list' => 'Lista',
  'exists locally' => 'istnieje lokalnie',
  'created locally' => 'utworzono lokalnie',
  'Remote list' => 'Zdalna lista',
  'not created' => 'nie utworzono',
  'Copying attributes' => 'Kopiowanie atrybutów',
  'Attribute' => 'Atrybut',
  'Copying users' => 'Kopiowanie użytkowników',
  'overwriting local data' => 'nadpisywanie danych lokalnych',
  'keeping local data' => 'zachowywanie danych lokalnych',
  'is a new user' => 'jest nowym użytkownikiem',
  'Error, no mapped attribute for' => 'Błąd, brak zamapowanych atrybutów dla',
  'Error, no local list defined for' => 'Błąd, nie zdefiniowano list lokalnych dla',
  'No lists available' => 'Brak dostępnych list',
  'Done' => 'Gotowe',
  'new users' => 'nowych użytkowników',
  'and' => 'oraz',
  'existing users' => 'istniejących użytkowników',
  'continue' => 'Kontynuuj',

);
?>