<?php
$lan = array(
  "Import emails from IMAP folders" => "Import adresów email z folderów IMAP",
  "No lists available" => "Brak dostępnych list",
  "Add a list" => "Dodaj listę",
  "personal" => "prywatny",
  "email" => "email",
  "folder" => "folder",
  "date" => "data",
  "can't connect" => "nie można połączyć się",
  "Processing" => "Przetwarzanie",
  "messages" => "wiadomości",
  "done" => "gotowe",
  "imap_getmailboxes failed" => "błąd imap_getmailboxes",
  "Please enter details of the IMAP account" => "Wprowadź detale konta IMAP",
  "Select the headers fields to search" => "Wybierz nagłówki pól wyszukiwania",
  "Select the lists to add the emails to" => "Wybierz listy, aby dodać adresy email",
  "Adding users to list" => "Dodawanie użytkowników do listy",
  "Mark new users as HTML" => "Oznacz nowych użytk. jako HTML",
/* read lines below as sentences: if you check 'overwrite' information about a user... etc. */
  "If you check" => "Jeśli zaznaczysz",
  "Overwrite Existing" => "Nadpisz istniejące",
  "information about a user in the database will be replaced by the imported information. Users are matched by email." => "informacje o użytkowniku w bazie danych zostaną zastąpione importowanymi informacjami. Użytkownicy są dopasowywani po adreseie email.",
  "Only use complete addresses" => "Tylko pełne adresy",
  "addresses that do not have a real name will be ignored. Otherwise all emails will be imported." => "adresy, które nie posiadają prawdziwej nazwy zostaną zignorowane. Jeśli nie zaznaczysz tej opcji wszystkie adresy będą importowane.",
  "If you choose" => "Jeśli wybierzesz",
  "send notification email" => "wyślij potwierdzenie",
  "the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails." => "użytkownicy, których dodajesz otrzymają prośbę o potwierdzenie rejestracji, na które będą musieli odpowiedzieć. Jest to zalecane, bo dzięki temu będzie można zidentyfikować nieprawidłowe adresy email.",
  "Send&nbsp;Notification&nbsp;email&nbsp;" => "Wyślij potwierdzenie",
  "Make confirmed immediately" => "Oznacz użytkowników jako potwierdzonych",
  "import3info" => "Istnieją dwie mozliwości dodania nazw użytkowników:
 albo jeden atrybut dla całej nazwy albo dwa atrybuty, jeden dla imienia i jeden dla nazwiska. 
Jeśli użyjesz 'dwóch atrybutów', nazwa zostanie podzielona po pierwszej spacji.",
  "Use one attribute for name" => "Użyj jednego atrybutu dla nazwy",
  'Use two attributes for the name' => 'Użyj dwóch atrybutów dla nazwy',
  "Attribute one" => "Pierwszy atrybut",
  "Create Attribute" => "Utwórz atrybut",
  "Attribute two" => "Drugi atrybut",
  "Cannot continue" => "Nie można kontynuować",
  "ok" => "ok",
  "failed" => "błąd",
  "Processed" => "Przetworzono",
  "folders and" => "pliki oraz",
  "unique emails found" => "znaleziono pojedyncze adresy email",
  "list" => "lista",
  "lists" => "listy",
  "new email was" => "nowy adres email",
  "new emails were" => "nowe adresy email",
  "email was" => "adres był",
  "emails were" => "adresów było",
  "All the emails already exist in the database and are members of the" => "Wszystkie adresy email istnieją już w bazie i są członkami",
  "succesfully imported to the database and added to" => "z sukcesem zaimportowano do bazy i dodano do",
  "subscribed to the" => "zasubskrybowano do",
  "emails already existed in the database" => "adresy email już istnieją w bazie",
  "Invalid Emails found." => "Znaleziono nieprawidłowe adresy email.",
  "These records were added, but the email has been made up. You can find them by doing a search on" => "Rekordy zostały dodane ale adresy email zostały wygenerowane. Aby je znaleźć poszukaj",
  "These records were deleted. Check your source and reimport the data. Duplicates will be identified." => "Rekordy zostały usunięte. Sprawdź źródło i zaimportuj dane ponownie. Duplikaty zostaną wykryte.",
  "No emails found" => "Nie znaleziono adresó email",
  "Import some more emails" => "Zaimportuj więcej adresów email",
  'Server' => 'Serwer',
  'User' => 'Użytkownik',
  'Password' => 'Hasło',
  'Continue' => 'Kontynuuj',
  'Process Selected Folders' => 'Przetwarzaj wybrane foldery',
);
?>