<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Nie posiadasz wystarczających uprawnień aby wyświetlić tą stronę',
  'Add a user' => 'dodaj użytkownika',
  'add user' => 'Dodaj użytkownika',
  'Members of' => 'Członkowie',
  'Tag all users in this page' => 'Zaznacz wszystkich użytkowników na tej stronie',
  'back to this list' => 'powrót do listy',
  'Download users on this list as a CSV file' => 'Pobierz użytkowników tej listy do pliku CSV',
  'Please enter a listid' => 'Wprowadź identyfikator listy',
  'Processing' => 'Przetwarzam',
  'users were moved to' => 'użytkownicy zostali przeniesieni do',
  'users were copied to' => 'użytkownicy zostali skopiowani do',
  'users were deleted from this list' => 'użytkownicy zostali usunięci z tej listy',
  'Users found, click add to add this user' => 'Znaleziono użytkowników, kliknij Dodaj aby dodać użytkownika',
  'Add' => 'Dodaj',
  'No user found with that email' => 'Nie znaleziono użytkowników z tym adresem email',
  'Inserting user' => 'Wstawianie użytkownika',
  'User added' => 'Użytkownik dodany',
  'Deleting' => 'Usuwanie',
  'Done' => 'Gotowe',
  'Users on this list' => 'Użytkowników na tej liście',
  'Listing user' => 'Wyświetl użytkownika',
  'to' => 'do',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Wyświetl użytkowników 1 do 50',
  'Members' => 'Członkowie',
  'confirmed' => 'potwierdzony',
  'tag' => 'oznacz',
  'del' => 'usuń',
  'Delete'=>'Usuń',
  '# msgs' => '# wiad.',
  '# rss' => '# rss',
  'rss freq' => 'częstotliwość rss',
  'last sent' => 'ostatnio wysłano',
  'What to do with "Tagged" users' => 'Co zrobić z oznaczonymi użytkownikami',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Przetworzeni zostaną tylko użytkownicy na tej stronie, którzy mają zaznaczone pole "oznacz"',
  'delete' => 'Usuń',
  'Move' => 'Przenieś',
  'Copy' => 'Kopiuj',
  'Nothing' => 'Nic',
  'to' => 'do', # as in destination
  'from this list' => 'z tej listy',
  'What to do with all users' => 'Co zrobić ze wszystkimi użytkownikami',
  'This will process all users on this list' => 'Przetworzeni zostaną wszyscy użytkownicy z listy',
  'do it' => 'wykonaj',
  
  
);
?>