<?php
$lan = array(
 'Please select a message to display' => 'Wybierz wiadomość do wyświetlenia',
 'Attachments for this message' => 'Załączniki tej wiadomości',
 'No attachments' => 'Brak załączników',
 'Filename' => 'Nazwa pliku',
 'Size' => 'Rozmiar',
 'Mime Type' => 'Typ Mime',
 'Description' => 'Opis',
 'Lists this message has been sent to' => 'Ta wiadomość została wysłana do nast. list',
 'None yet' => 'None yet',
 'Send this (same) message to (a) new list(s)' => 'Wyślik tą samą wiadomość do kolejnych list',
 'List is Active' => 'Lista jest aktywna',
 'List is not Active' => 'Lista jest nieaktywna',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Uwaga:</b> ta wiadomośc została już wysłana do wszystkich list. Aby wysłać ją ponownie do nowych użytkowników użyj funkcji "Kolejkuj ponownie"',
 'Resend' => 'Wyślij ponownie',
 'id' => 'id',
 'subject' => 'temat',
 'from field' => 'pole od',
 'to field' => 'pole do',
 'reply to' => 'odpowiedź do',
 'message' => 'wiadomość',
 'textmessage' => 'wiadomość tekstowa',
 'footer' => 'stopka',
 'entered' => 'wprowadzono',
 'modified' => 'zmodyfikowano',
 'embargo' => 'ograniczenie do',
 'repearinterval' => 'interwał powtórzeń',
 'repeatuntil' => 'powtarzaj do',
 'status' => 'status',
 'userselection' => 'wybór użytkownika',
 'sent' => 'wysłano',
 'htmlformatted' => 'sformatowano w html',
 'sendformat' => 'format wysyłania',
 'template' => 'szablon',
 'processed' => 'przetworzono',
 'as text' => 'jako tekst',
 'as html' => 'jako html',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'as pdf' => 'jako pdf',
 'as text and pdf' => 'jako text i pdf',
 'viewed' => 'wyświetlano',
 'bounce count' => 'liczba zwrotów',
 'send start' => 'początek wysyłania',
 'RSS template' => 'szablon RSS',
 'owner' => 'właściciel',

 # new in 2.10.1
 'edit this message' => 'Edytuj tą wiadomość',
);
?>
