<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'uruchomiono w trybie testowym. Wiadomości nie będą wysyłane. Sprawdź plik konfiguracyjny.',
'The following restrictions have been set by your ISP:' => 'Następujące ograniczenia zostału ustawione przez Twojego dostawcę Internetu:',
'Script stage' => 'Etap skryptu',
'Finished, Nothing to do' => 'Ukończono, nie ma nic do zrobienia',
'messages sent in' => 'wiadomości wysłano w',
'seconds' => 'sekund',
'invalid emails' => 'nieprawidłowych adresów email',
'emails failed (will retry later)' => 'adresów, na które nie mozna było wysłać (próba zostanie powtórzona później)',
'emails unconfirmed (not sent)' => 'niepotwierdzonych adresów email (nie wysłano)',
'Warning: script never reached stage 5' => 'Uwaga: skrypt nie osiągnął etapu 5',
'This may be caused by a too slow or too busy server' => 'Może to być spowodowane przez zbyt wolny lub zbyt zajęty serwer',


'In safe mode, batches are set to a maximum of 100' => 'W trybie awaryjnym, partie są ustawione maksymalnie na 100',
'Running in safe mode' => 'uruchomiono w trybie awaryjnym',
'msgs/hr' => 'wiad/godz.',
'Reload required' => 'Konieczne przeładowanie',
'Finished, All done' => 'Ukończono, Wszystko zrobione.',
'Script finished, but not all messages have been sent yet.' => 'Skrypt ukończony ale nie wszystkie wiadomości zostały jeszscze wysłane.',
'Finished this run' => 'Zakończono to uruchomienie',
'(test)' => '(test)',
'Would have sent' => 'Zostałoby wysłane',
'(test)' => '(test)',
'Would have sent' => 'Zostałoby wysłane',
'Started' => 'Uruchomiono',
'Processing has been suspended by your ISP, please try again later' => 'Przetwarzanie zostało wstrzymane przez dostawę Internetu, spróbuj później',
'Sending in batches of' => 'Wysyłanie w partiach ',
'emails' => 'emaili',
'This batch will be' => 'W tej partii będzie',
'emails, because in the last' => 'emaili, ponieważ jest ostatnia',
'emails were sent' => 'emaili wysłano',
'Sending in batches of' => 'Wysyłanie w partiach ',
'emails' => 'emaili',
'In the last' => 'W ostatnich',
'seconds more emails were sent' => 'sekundach zostało wysłanych więcej emaili',
'than is currently allowed per batch' => 'niż jest to obecnie dozwolone w partii',
'Sent in last run' => 'Wysłano w ostatnim uruchomieniu',
'Skipped in last run' => 'Pominięto w ostatnim uruchomieniu',
'Processing has started,' => 'Uruchomiono przetwarzanie,',
'message(s) to process.' => 'wiadomości do przetworzenia.',
'It is safe to click your stop button now, report will be sent by email to' => 'Teraz możesz kliknąć przycisk "stop", raport zostanie wysłany pocztą na adres',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Twój serwer WWW jest uruchomiony w trybie awaryjnym. Zostaw to okno otwarte. Może ono przeładowywać się kilka razy aby ubyła pewność, że wszystkie wiadomości zostały wysłane.',
'Reports will be sent by email to' => 'Raport zostanie wysłany pocztą na adres',
'Processing message' => 'Przetwarzanie wiadomości nr',
'Message' => 'Wiadomość',
'is an RSS feed for' => 'jest nagłówkiem RSS dla',
'Looking for users' => 'Wyszukiwanie użytkowników',
'users apply for attributes, now checking lists' => 'wybrane atrybuty użytkownika są odpowiednie, sprawdzanie list',
'No users apply for attributes' => 'Żaden użytkownik nie pasuje do wybranych atrybutów',
'looking for users who can be excluded from this mailing' => 'Poszukiwanie użytkowników, którzy mogą zostać wyłączeni z tego przetwarzania',
'Process Killed by other process' => 'Proces został zakończony przez inny proces',
'Found them' => 'Znaleziono',
'to process' => 'do przetworzenia',
'No users to process for this batch' => 'Brak użytkowników do przetworzenia w tej partii',
'batch limit reached' => 'osiągnięto limit partii',
'Process Killed by other process' => 'Proces został zakończony przez inny proces',
'Message I was working on has disappeared' => 'Przetwarzana wiadomość zniknęła',
'Sending' => 'Wysyłanie',
'It took' => 'Minęło',
'seconds to send' => 'sekund podczas wysyłania',
'Failed sending to' => 'Nie powiodło się wysyłanie do',
'Unconfirmed user' => 'Użytkownik niepotwierdzony',
'Not sending to' => 'Nie wysłano do',
'already sent' => 'wysłano',
'Processed' => 'Przetworzono',
'out of' => 'z',
'Hmmm, No users found to send to' => 'Hmmm, nie znaleziono użytkowników aby wysłać',
'It took' => 'Minęło',
'to send this message' => 'podczas wysyłania tej wiadomości',
'waiting for' => 'oczekiwanie na',
'to make sure we don\'t exceed our limit of' => 'aby być pewnym, że nie przekroczymy limitu',
'messages in' => 'wiadomości w',

### new in 2.9.5
'Message Sending has started' => 'Rozsyłanie wiadomości rozpoczęte',
'phplist has started sending the message with subject %s' => 'phplist - rozpoczęto rozsyłanie wiadomości o temacie %s',
'to view the progress of this message, go to %s' => 'aby obejrzeć postęp wysyłania kliknij %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'Ponad 10 razy próbowano wysłać do %s. Próby te zostały zablokowane poprzez przepustowość domeny.',
'Introducing extra delay to decrease throttle failures' => 'Wprowadzanie dodatkowego opóźnienia aby obniżyć błędy przepustowości',
'%s is currently over throttle limit of %d per %d seconds' => '%s jest aktualnie ponad limit przepustowości %d na %d sekund',
'not sending to ' => 'nie wysyłam do ',
'Message Sending has finished' => 'Ukończono wysyłanie wiadomości',
'phplist has finished sending the message with subject %s' => 'phplist - zakończono wysyłanie wiadomości o temacie %s',

'Sending of this message has been suspended' => 'Wysyłanie tej wiadomości zostało wstrzymane',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'Wysłano mniej niz w partii, więc przeładowuje natychmiast',
'Waiting for %d seconds before reloading' => 'oczekiwanie %d sekund przed przeładowaniem',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Pozostaw to okno otwarte. Rozpocząłeś przetwarzanie partii, więc okno będzie się przeładowywało kilka razy aby wysłać wiadomości. Raport zostanie wysłany pocztą na adres',

);

?>