<?php 
$lan = array(

  'add_list' => 'افزودن یک فهرست', //duplicated in import1_text
  'cannot connect to remote database' => 'نمیتوانم به پایگاه داده دور متصل شوم',
  'No users to copy, is the prefix correct?' => 'کاربری برای کپی کردن پیدا نشد، پیشوند درست است؟',
  'Please enter details of the remote Server' => 'لطفا جزئیات سرور دور را وارد کنید',
  'Server:' => 'سرور:',
  'user' => 'کاربر:',
  'Password:' => 'گذرواژه:',
  'Database Name:' => 'نام پایگاه داده:',
  'Table prefix:' => 'پیشوند جدول:',
  'Usertable prefix:' => 'پیشوند جدول کاربر:',
  'select_lists' => 'فهرستها را انتخاب کنید تا ایمیلها به آنها افزوده شود',
  'Copy lists from remote server (lists are matched by name)' => 'کپی کردن فهرستها از سرور دور (فهرستها بر پایه نام تطبیق داده میشوند)',
  'Mark new users as HTML:' => 'کاربرهای جدید را برای HTML علامت بزن:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'اگر "بازنویسی" را انتخاب کنید، اطلاعات کاربرها در پایگاه داده با اطلاعات وارد شده جایگزین میشوند. کاربرها بر پایه ایمیل تطبیق داده میشوند.',
  'Overwrite Existing:' => 'بازنویسی:',
  'Making connection with remote database' => 'در حال ارتباط با پایگاه داده دور',
  'Getting data from ' => 'در حال دریافت اطلاعات از ',
  'Remote version is' => 'ویرایش دور ',
  'Remote version has' => 'در ویرایش دور',
  'users' => 'کاربرها',
  'lists' => 'فهرستها',
  'Copying lists' => 'در حال کپی کردن فهرستها',
  'list' => 'فهرست',
  'exists locally' => 'در محل موجود است',
  'created locally' => 'در محل ایجاد شد',
  'Remote list' => 'فهرست دور',
  'not created' => 'ایجاد نشد',
  'Copying attributes' => 'در حال کپی کردن ویژگیها',
  'Attribute' => 'ویژگی',
  'Copying users' => 'در حال کپی کردن کاربرها',
  'overwriting local data' => 'در حال بازنویسی داده های محلی',
  'keeping local data' => 'حفظ داده محلی',
  'is a new user' => 'یک کاربر جدید است',
  'Error, no mapped attribute for' => 'خطا، ویژگی مرتبطی وجود ندارد برای',
  'Error, no local list defined for' => 'خطا، فهرست محلی وجود ندارد برای',
  'No lists available' => 'فهرستی موجود نیست',
  'Done' => 'انجام شد',
  'new users' => 'کاربرهای جدید',
  'and' => 'و',
  'existing users' => 'کاربرهای موجود',
  'continue' => 'ادامه',

);
?>