<?php 
$lan = array(
  "NoRecord" => "Ni takega zapisa",
  "BackToBList" => "Nazaj na seznam odbojev",
  "NotFound" => "Ni najdeno<br/>",
  "AddedToB" => "Dodano %s štetju odbojev za uporabnika %s<br/>",
  "NotAddedToB" => "Ne morem dodati %s štetju odbojev za uporabnika %s<br/>",
  "MadeUnconfirmed" => "%s uporabnikov nastavljeno kot nepotrjenih<br/>",
  "MadeUserRText" => "%s uporabnikov nastavljeno, da prejema sporočila kot tekst<br/>",
  "DelUser" => "Izbriši uporabnika %s<br/>",
  "DeletingB" => "Brišem odboje %s ..\n",
  "DoneAndLoading" => "..Končano, nalagam naslednji odboj..",
  "NoSRecord" => "Ni takega zapisa",
  "PossibleActions" => "Možne akcije:",
  "ForUser" => "Za uporabnika z e-pošto",
  "IncreaseB" => "Povečaj štetje odbojev z",
  "IncreaseBNote" => "(uporabi negativno število za zmanjšanje)",
  "MarkAsUnconfirmed" => "Označi uporabnika kot nepotrjenega",
  "MarkAsUnconfirmedNote" => "(da lahko pošlješ zahtevek za potrditev)",
  "SetReceiveText" => "Nastavi, da uporabnik prejema sporočila kot tekst namesto HTML",
  "DelUser1" => "Izbriši uporabnika",
  "DelAndGo" => "Izbriši ta odboj in pojdi na naslednjega",
  "DoAbove" => "Naredi zgornje",
  "BounceDetails" => "Podrobnosti odboja:",
  "ID" => "ID",
  "Date" => "Datum",
  "Status" => "Status",
  "Comment" => "Komentar",
  "Header" => "Header",
  "Body" => "Body",
  
  # new in 2.9.5
  'Regular Expression' => 'Regularni izraz',
  'Action' => 'Akcija',
  'Memo for this rule' => 'Zapis za to pravilo',
  'Add new Rule' => 'Dodaj pravilo',
  'Create New Rule based on this bounce' => 'Ustvari novo pravilo, osnovano na tem odboju',
);
?>