<?php
$lan = array( 
 'checklist for installation' => 'Checklist for Installation',
 'cannot be empty' => 'Ne more biti prazno',
 'editing' => 'Urejanje',
 'save changes' => 'Shrani spremembe',
 'edit' => 'Uredi',

  # added 24 May 2006
  'delete user' => 'Izbriši uporabnika',
  'unconfirm user' => 'Določi uporabnika kot nepotrjenega',
  'blacklist user' => 'Dodaj uporabnika na ČRNO listo',
  'delete user and bounce' => 'Izbriši uporabnika in odboj',
  'unconfirm user and delete bounce' => 'Izbriši odboj in določi uporabnika kot nepotrjenega',
  'blacklist user and delete bounce' => 'Dodaj uporabnika na ČRNO listo in izbriši odboj',
  'delete bounce' => 'Izbriši odboj',
  'Website address (without http://)' => 'Naslov spletne strani (brez http://)',
  'Domain Name of your server (for email)' => 'Domensko ime strežnika (za e-pošto)',
  'Person in charge of this system (one email address)' => 'Oseba zadolžena za sistem (samo ena e-pošta)',
  'How often do you want to check for a new version of phplist (days)' => 'kako pogosto želite preveriti za novo verzijo PHPliste (v dnevih)',
  'List of people to CC in system emails (separate by commas)' => 'CC Osebe za pošiljanje sistemskih e-sporočil, e-pošte ločene z vejico)',
  'Who gets the reports (email address, separate multiple emails with a comma)' => 'Kdo dobiva poročila (e-pošte ločene z vejico)',
  'From email address for system messages' => 'Od: e-pošta za sistemska sporočila',
  'What name do system messages appear to come from' => 'Ime e-naslova za sistemska sporočila',
  'Reply-to email address for system messages' => 'Odgovor za: e-pošta za sistemska sporočila',
  'if there is only one visible list, should it be hidden in the page and automatically
    subscribe users who sign up (0/1)' => 'Če je vidna le ena kategorija novic, ali naj bo skrita na naročnišči strani in naj se naročniki samodejno včlanijo vanjo? (0/1)',
  'width of a textline field (numerical)' => 'Širina polja za tekst (številka)',
  'dimensions of a textarea field (rows,columns)' => 'Dimenzije področja za tekst (vrstice,kolone)',
  'Does the admin get copies of subscribe, update and unsubscribe messages (0/1)' => 'Ali administrator dobi kopije sporočil za prijavo, odjavo in urejanje uporabnikov? (0/1)',
  'The default subscribe page when there are multiple' => 'Privzeta stran za naročanje, če je strani več',
  'The default HTML template to use when sending a message' => 'Privzeta HTML predloga za pošiljanje sporočil',
  'URL where users can subscribe' => 'URL kjer se uporabniki lahko prijavijo',
  'URL where users can unsubscribe' => 'URL kjer se uporabniki lahko odjavijo',
  'URL where users have to confirm their subscription' => 'URL kjer uporabniki potrdijo svojo prijavo',
  'URL where users can update their details' => 'URL kjer uporabniki lahko uredijo svoje podatke',
  'URL where messages can be forwarded' => 'URL kjer se sporočila lahko pošljejo naprej',
  'Subject of the message users receive when they subscribe' => 'Zadeva potrditvenega sporočila za prijavo',
  'Message users receive when they subscribe' => 'Telo potrditvenega sporočila za prijavo',
  'Subject of the message users receive when they unsubscribe' => 'Zadeva sporočila pri odjavi uporabnika',
  'Message users receive when they unsubscribe' => 'STelo sporočila pri odjavi uporabnika',
  'Subject of the message users receive after confirming their email address' => 'Zadeva sporočila, ko uporabniki potrdijo svojo e-pošto',
  'Message users receive after confirming their email address' => 'Telo sporočila za uporabnike, ko potrdijo svojo e-pošto',
  'Subject of the message users receive when they have changed their details' => 'Zadeva sporočila, ko uporabniki spremenijo svoje podatke',
  'Message that is sent when users change their information' => 'Telo sporočila za uporabnike, ko spremenijo svoje podatke',
  'Part of the message that is sent to their new email address when users change their information, and the email address has changed' => 'Del sporočila, ki ga uporabniki dobijo na svoj nov e-naslov, ko spremenijo svoje podatke in je bil spremenjen e-naslov',
  'Part of the message that is sent to their old email address when users change their information, and the email address has changed' => 'Del sporočila, ki ga uporabniki dobijo na svoj stari e-naslov, ko spremenijo svoje podatke in je bil spremenjen e-naslov',
  'Subject of message to send when users request their personal location' => 'Zadeva sporočila, ki ga uporabniki dobijo, ko zahtevajo svojo osebno lokacijo',
  'Message to send when they request their personal location' => 'Telo sporočila, ki ga uporabniki dobijo, ko zahtevajo svojo osebno lokacijo',
  'Default footer for sending a message' => 'Privzeta noga za pošiljanje sporočil',
  'Footer used when a message has been forwarded' => 'Noga za uporabo, ko se sporočilo pošilja naprej',
  'Header of public pages. The header should start with &lt;/head&gt; . You can add header elements, but don\'t add the title or other basic header elements.' => 'Glava javnih strani. Glava naj se začne z &lt;/head&gt; . Lahko dodajaš header elemente, ampak ne dodajaj title ali drugih osnovnih header elementov.',
  'Footer of public pages' => 'Noga javnih strani',
  'Charset for HTML messages' => 'Set karakterjev za HTML sporočila',
  'Charset for Text messages' => 'Set karakterjev za tekstovna sporočila',
  'CSS for HTML messages without a template' => 'CSS za HTML sporočila brez predloge',
  'Domains that only accept text emails, one per line' => 'Domene, ki sprejemajo le tekstovna sporočila, ena v vrstici',
  'Minimum amount of items to send in an RSS feed' => 'Najmanjše število predmetov za pošiljanje v RSS viru',
  'Template for text item in RSS feeds' => 'Predloga za tekst predmet v RSS virih',
  'Template for HTML item in RSS feeds' => 'Predloga za HTML predmet v RSS virih',
  'Maximum amount of items to send in an RSS feed' => 'Največje število predmetov za pošiljanje v RSS viru',
  'Template for separator between feeds in RSS feeds (text)' => 'Template for separator between feeds in RSS feeds (text)',
  'Template for separator between feeds in RSS feeds (HTML)' => 'Template for separator between feeds in RSS feeds (HTML)',
  'Width in px of FCKeditor Area' => 'Širina v px za FCKeditor področje',
  'Height in px of FCKeditor Area' => 'Višina v px za FCKeditor področje',
);
?>