<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Your database is out of date, please make sure to upgrade',
  'Your version' => 'Vaša verzija',
  'Latest version' => 'Zadnja verzija',
  'phplist version' => '<a href="http://www.phplist.com">phplist</a> version',
  'Database has not been initialised' => 'Database has not been initialised',
  'go to' => 'Pojdi na',
  'Initialise Database' => 'Initialise Database',
  'to continue' => 'za nadaljevanje',
  'A new version of PHPlist is available!' => 'A new version of PHPlist is available!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible',
  'View what has changed' => 'Pogled se je spremenil',
  'Download' => 'Prenesi',
  'System Functions' => 'Sistemske funkcije',
  'Setup ' => 'Nastavitev ',
  'Check Database structure' => 'Preveri strukturo podatkovne baze',
  'View the eventlog' => 'Dnevnik dogodkov',
  'Configuration functions' => 'Konfiguracijske funkcije',
  'Configure Attributes' => 'Urejanje atributov',
  'Control values for' => 'Uredi vrednosto za',
  'Control values for' => 'Uredi vrednosto za',
  'Control values for' => 'Uredi vrednosto za',
  'Configure Subscribe pages' => 'Uredi strani za vpis članov',
  'List and user functions' => 'Kategorije in Uporabniki',
  'List the current lists' => 'Seznam kategorij novic',
  'List all Users' => 'Seznam vseh uporabnikov',
  'Reconcile the user database' => 'Uredi bazo uporabnikov',
  'Import Users' => 'Uvozi uporabnike',
  'Export Users' => 'Izvozi uporabnike',
  'Administrator functions' => 'Administrator',
  'Add, edit and remove Administrators' => 'Dodaj, uredi ali izbriši administratorja',
  'Configure attributes for administrators' => 'Uredi atribute za administratorje',
  'Message functions' => 'Sporočila',
  'Configure Templates' => 'Uredi predloge',
  'List all Messages' => 'Prikaži vsa sporočila',
  'Process the Message queue' => 'Začni pošiljanje sporočil',
  'RSS Functions' => 'RSS Funkcije',
  'Get RSS feeds' => 'Get RSS feeds',
  'View RSS items' => 'View RSS items',
  'Plugins' => 'Plugins',
  'Upgrade' => 'Upgrade',
'Change your details (e.g. password)' => 'Spremeni svoje podrobnosti (npr. geslo)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'You have set TEST in config.php to 1, so it will only show what would be sent',

  # added at a later stage
  'setup' => 'Nastavitev',
  'upgrade' => 'Nadgradnja',
  'dbcheck' => 'Preveri podatkovno bazo',
  'eventlog' => 'Dnevnik dogodkov',
  'attributes' => 'Atributi',
  'spage' => 'Naročniške strani',
  'list' => 'Kategorije',
  'reconcileusers' => 'Uredi uporabnike',
  'import' => 'Uvoz',
  'export' => 'Izvoz',
  'admins' => 'Administratorji',
  'adminattributes' => 'Atributi administratorjev',
  'send' => 'Pošlji',
  'templates' => 'Predloge',
  'processqueue' => 'Začni pošiljanje sporočil',
  'processbounces' => 'Obdelaj odboje',
  'getrss' => 'getrss',
  'viewrss' => 'viewrss',
  'admin' => 'Administrator',
  'preparesend' => 'Pripravi za pošiljanje',
  'sendprepared' => 'Pripravljeno za pošiljanje',


);

?>