<?php
$lan = array(
  'You do not have enough priviliges to view this page' => 'Nimate pravic za ogled te strani',
  'Add a user' => 'Dodaj uporabnika',
  'add user' => 'Dodaj uporabnika',
  'Members of' => 'Člani od',
  'Tag all users in this page' => 'Označi vse uporabnike na tej strani',
  'back to this list' => 'Nazaj na to kategorijo',
  'Download users on this list as a CSV file' => 'Prenesi uporabnike te kategorije v CSV datoteko',
  'Please enter a listid' => 'Vnesi ID kategorije',
  'Processing' => 'Obdelujem',
  'users were moved to' => 'Uporabniki so bili premaknjeni v',
  'users were copied to' => 'Uporabniki so bili skopirani v',
  'users were deleted from this list' => 'Uporabniki so bili izbrisani iz kategorije',
  'Users found, click add to add this user' => 'Uporabniki najdeni, klikni dodaj za dodajanje tega uporabnika',
  'Add' => 'Dodaj',
  'No user found with that email' => 'Ni uporabnika s to e-pošto',
  'Inserting user' => 'Vnašam uporabnika',
  'User added' => 'Uporabnik dodan',
  'Deleting' => 'Brišem',
  'Done' => 'Končano',
  'Users on this list' => 'Uporabniki v kategoriji',
  'Listing user' => 'Prikazujem uporabnika',
  'to' => 'do',//in sentence 'listing user 1  to  50'
  'Listing user 1 to 50' => 'Prikazujem uporabnike 1 do 50',
  'Members' => 'Člani',
  'confirmed' => 'Potrjen',
  'tag' => 'Označi',
  'del' => 'izbriši',
  'Delete'=>'Izbriši',
  '# msgs' => '# msgs',
  '# rss' => '# rss',
  'rss freq' => 'rss freq',
  'last sent' => 'Zadnje poslano',
  'What to do with "Tagged" users' => 'Z označenimi uporabniki',
  'This will only process the users in this page that have the "Tag" checkbox checked' => 'Obdelani bodo le označeni uporabniki',
  'delete' => 'Izbriši',
  'move' => 'Premakni',
  'copy' => 'Kopiraj',
  'nothing' => 'Nič',
  'to' => 'v', # as in destination
  'from this list' => 'iz te kategorije',
  'What to do with all users' => 'Z uporabniki',
  'This will process all users on this list' => 'Obdelani bodo vsi uporabniki v tej kategoriji',
  'do it' => 'Naredi',
  
  
);
?>