<?php
$lan = array(
 'Please select a message to display' => 'Izberite sporočilo za prikaz',
 'Attachments for this message' => 'Priponke za to sporočilo',
 'No attachments' => 'Ni priponk',
 'Filename' => 'Datoteka',
 'Size' => 'Velikost',
 'Mime Type' => 'Mime Type',
 'Description' => 'Opis',
 'Lists this message has been sent to' => 'Kategorije, ki jim je bilo sporočilo poslano',
 'None yet' => 'Še nobeni',
 'Send this (same) message to (a) new list(s)' => 'Pošlji to enako sporočilo tudi drugim kategorijam',
 'List is Active' => 'Kategorija je aktivna',
 'List is not Active' => 'Kategorija ni aktivna',
 '<b>Note:</b> this message has already been sent to all lists. To resend it to new users use the "Requeue" function.' => '<b>Pozor:</b> To sporočilo je bilo že poslano vsem kategorijam. Za pošiljanje novim uporabnikom uporabi funkcijo - Ponovno postavi v vrsto za pošiljanje.',
 'Resend' => 'Ponovno pošlji',
 'id' => 'ID',
 'subject' => 'Zadeva',
 'fromfield' => 'polje Od',
 'tofield' => 'polje Za',
 'replyto' => 'Odgovor za',
 'message' => 'Sporočilo',
 'textmessage' => 'Tekstovno sporočilo',
 'footer' => 'Noga',
 'entered' => 'Vnešeno',
 'modified' => 'Spremenjeno',
 'embargo' => 'Zakasnjeno',
 'repeatinterval' => 'Ponovi interval',
 'repeatuntil' => 'Ponavljaj do',
 'status' => 'Status',
 'userselection' => 'Izbira uporabnika',
 'sent' => 'Poslano',
 'htmlformatted' => 'HTML format',
 'sendformat' => 'Format za pošiljanje',
 'template' => 'Predloga',
 'processed' => 'Obdelano',
 'astext' => 'Kot tekst',
 'ashtml' => 'Kot HTML',
// 'astextandhtml' => 'as text and html', //obsolete by bug 0009687
 'aspdf' => 'Kot pdf',
 'astextandpdf' => 'Kot tekst in pdf',
 'viewed' => 'Ogledano',
 'bouncecount' => 'Št. odbojev',
 'sendstart' => 'Začetek pošiljanja',
 'rsstemplate' => 'RSS Predloga',
 'owner' => 'Lastnik',

 # new in 2.10.1
 'edit this message' => 'Uredi to sporočilo',
);
?>
