<?php

$lan = array(
'Running in testmode, no emails will be sent. Check your config file.' => 'Running in testmode, no emails will be sent. Check your config file.',
'The following restrictions have been set by your ISP:' => 'The following restrictions have been set by your ISP:',
'Script stage' => 'Stanje skripte',
'Finished, Nothing to do' => 'Končano, Nimam nič za početi',
'messages sent in' => 'sporočila poslana v',
'seconds' => 'sekundah',
'invalid emails' => 'neveljavne e-pošte',
'emails failed (will retry later)' => 'spodletele e-pošte (ponoven poizkus kasneje)',
'emails unconfirmed (not sent)' => 'nepotrjene e-pošte (ni poslano)',
'Warning: script never reached stage 5' => 'Opozorilo: skripta ni nikoli dosegla nivoja 5',
'This may be caused by a too slow or too busy server' => 'Vzrok je lahko prepočasen ali preveč zaseden strežnik',


'In safe mode, batches are set to a maximum of 100' => 'In safe mode, batches are set to a maximum of 100',
'Running in safe mode' => 'Running in safe mode',
'msgs/hr' => 'sporočil/uro',
'Reload required' => 'Potreben Ponovni zagon ',
'Finished, All done' => 'Končano, Vse urejeno',
'Script finished, but not all messages have been sent yet.' => 'Skript končan, vendar vsa sporočila še niso bila poslana.',
'Finished this run' => 'Konec te runde',
'(test)' => '(test)',
'Would have sent' => 'Would have sent',
'(test)' => '(test)',
'Would have sent' => 'Would have sent',
'Started' => 'Začeto',
'Processing has been suspended by your ISP, please try again later' => 'Obdelavo je prekinil vaš ISP. Poizkusite kasneje.',
'Sending in batches of' => 'Pošiljanje svežnjev po',
'emails' => 'e-pošt',
'This batch will be' => 'Ta sveženj bo',
'emails, because in the last' => 'e-pošt, ker je v zadnjem',
'emails were sent' => 'e-pošt poslanih',
'Sending in batches of' => 'Pošiljam v svežnjih po',
'emails' => 'e-pošt',
'In the last' => 'V zadnjih',
'seconds more emails were sent' => 'sekundah je bilo poslanih še več e-pošt',
'than is currently allowed per batch' => 'kot je trenutno dovoljeno na sveženj',
'Sent in last run' => 'Poslano v zadnji rundi',
'Skipped in last run' => 'Preskočeno v zadnji rundi',
'Processing has started,' => 'Obdelava se je začela,',
'message(s) to process.' => 'sporočil za obdelavo.',
'It is safe to click your stop button now, report will be sent by email to' => 'Sedaj je varno za klik na gumb "stop", poročilo bo poslano na e-pošto:',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Vaš strežnik teče v varnem načinu "safe_mode". Imejte to okno odprto. Lahko se večkrat osveži, da se prepričate, da so bila poslana vsa sporočila.',
'Reports will be sent by email to' => 'Poročila bodo poslana na e-pošto:',
'Processing message' => 'Obdelujem sporočilo',
'Message' => 'Sporočilo',
'is an RSS feed for' => 'is an RSS feed for',
'Looking for users' => 'Iščem uporabnike',
'users apply for attributes, now checking lists' => 'uporabniki ustrezajo atributem, sedaj preverjam kategorije',
'No users apply for attributes' => 'Noben uporabnik ne ustreza atributom',
'looking for users who can be excluded from this mailing' => 'Iščem uporabnike, ki so izključeni iz te obdelave',
'Process Killed by other process' => 'Proces končan zaradi drugega procesa',
'Found them' => 'Najdi jih',
'to process' => 'na proces',
'No users to process for this batch' => 'Ni uporabnikov za obdelavo za ta sveženj',
'batch limit reached' => 'limit svežnja dosežen',
'Process Killed by other process' => 'Proces končan zaradi drugega procesa',
'Message I was working on has disappeared' => 'Sporočilo na katerem sem delal je izginilo',
'Sending' => 'Pošiljam',
'It took' => 'Vzelo je',
'seconds to send' => 'sekund za pošiljanje',
'Failed sending to' => 'Napaka pri pošiljanju za',
'Unconfirmed user' => 'Nepotrjen uporabnik',
'Not sending to' => 'Ne pošiljam za',
'already sent' => 'Že poslano',
'Processed' => 'Obdelano',
'out of' => 'skupno od',
'Hmmm, No users found to send to' => 'Hmmm, ne najdem uporabnikov za pošiljanje',
'It took' => 'Vzelo je',
'to send this message' => 'za pošiljanje tega sporočila',
'waiting for' => 'čakam na',
'to make sure we don\'t exceed our limit of' => 'da se prepričam, da ne presežemo limita od',
'messages in' => 'sporočila v',

### new in 2.9.5
'Message Sending has started' => 'Pošiljanje sporočil se je pričelo',
'phplist has started sending the message with subject %s' => 'phplist je pričel s pošiljanjem sporočila z Zadevo %s',
'to view the progress of this message, go to %s' => 'Za ogled napredovanja tega sporočila pojdi na %s',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.',
'Introducing extra delay to decrease throttle failures' => 'Predstavitev dodatne zamude za zmanjšanje "throttle" napak',
'%s is currently over throttle limit of %d per %d seconds' => '%s je trenutno čez "throttle" limit od %d na %d sekund',
'not sending to ' => 'ne pošiljam za ',
'Message Sending has finished' => 'Pošiljanje sporočila je končano',
'phplist has finished sending the message with subject %s' => 'phplist je končal pošiljanje sporočila z Zadevo %s',

'Sending of this message has been suspended' => 'Pošiljanje tega sporočila je bilo odloženo',

# new in 2.10.1
'Less than batch size were sent, so reloading imminently' => 'Manj poslanih sporočil, kot določeno za sveženj, takoj ponovno nalagam',
'Waiting for %d seconds before reloading' => 'Čakam %d sekund pred nadaljevanjem',
'Please leave this window open. You have batch processing enabled, so it will reload several times to send the messages. Reports will be sent by email to' => 'Pustite to okno odprto ! Vključeno imate pošiljanje v svežnjih in okno se bo večkrat osvežilo, da bodo poslana vsa sporočila. Poročila bodo poslana na e-pošto:',

);

?>