<?php

$lan = array(
  'Email is a system attribute' => 'Email is een systeem attribuut',
  'Converting' => 'Omzetten',
  'from' => 'Van',
  'to' => 'Naar',
  'deleting' => 'verwijderen',
  'Cannot delete attribute, it is being used by the following forms:' => 'Kan attribuut niet verwijderen, het wordt gebruikt door de volgende form:',
  'Warning, changing types of attributes can take a long time' => 'Opgelet, Het veranderen van het type van het attribuut kan lang duren',
  'Sorry, merging of checkbox groups is not implemented yet' => 'Sorry, het samenvoegen van checkbox groepen wordt nog niet uitgevoerd',
  'cannot merge just one attribute' => 'Kan niet 1 attribuut samenvoegen',
  'Merging' => 'Samenvoegen',
  'into' => 'in',
  'Can only merge attributes of the same type' => 'Enkel attribuuten van hetzelfde typen kunnen worden samengevoegd',
  'Existing attributes' => 'Bestaande attributen',
  'No Attributes have been defined yet' => 'Er zijn nog geen attributen gedefinieerd',
  'Load data from' => 'Data laden van',
  'predefined defaults' => 'Vooraf bepaalde standaardwaarden',
  'Attribute' => 'Attribuut',
  'used in' => 'gebruikt in',
  'forms' => 'forms',
  'tag' => 'Markering', # action
  'name' => 'Naam',
  'Type' => 'Type', # as in aspect of, type of attribute
  'Default Value' => 'Standaard waarde',
  'Order of Listing' => 'Volgorde',
  'Is this attribute required?' => 'Is dit attribuut vereist?',
  'textline' => 'tekstlijn',
  'checkbox' => 'checkbox',
  'checkboxgroup' => 'checkboxgroep',
  'radio' => 'radio',
  'select' => 'selecteren',
  'hidden' => 'verborgen',
  'textarea' => 'tekstblok',
  'date' => 'datum',
  'savechanges' => 'Wijzigingen opslaan',
  'With TAGGED attributes' => 'Met GEMARKEERDE attributen',
  'delete' => 'Werwijder',
  'Merge' => 'Voeg samen',
  'Add new Attribute' => 'Voeg nieuw attribuut toe',
  'authoritative list' => 'authoritatieve lijst',
);

?>