<?php

# file with common texts for translation

$lan = array(
  'Logout' => 'log uit',
  'Main Page' => 'hoofdpagina',
  'Subscriber' => 'gebruiker',
  'Error' => 'Fout',
  'version' => 'versie',
  'powered by' => 'powered by',
  'Fatal Error' => 'Fatale Fout',
  'Warning' => 'Waarschuwing',
  'Information' => 'informatie',
  'help' => 'help',
  'about' => 'about',
  'lists' => 'lijsten',
  'send a message' => 'verzend een bericht',
  'Subscribers' => 'gebruikers',
  'manage users' => 'beheer gebruikers',
  'Campaigns' => 'berichten',
  'statistics' => 'statistieken',
  'process queue' => 'verwerk wachtrij',
  'configure' => 'configureer',
  'Subscribe Pages' => 'Inschrijf pagina&acute;s ',
  'Send a prepared message' => 'verzend een voorbereid bericht',
  'Prepare a message' => 'bereid een bericht voor',
  'Templates' => 'sjablonen',
  'View Bounces' => 'bekijk bounces',
  'Process Bounces' => 'verwerk bounces',
  'Eventlog' => 'logboek',
  'Sunday' => 'zondag',
  'Monday' => 'maandag',
  'Tuesday' => 'dinsdag',
  'Wednesday' => 'woensdag',
  'Thursday' => 'donderdag',
  'Friday' => 'vrijdag',
  'Saturday' => 'zaterdag',
  'January' => 'Januari',
  'February' => 'Februari',
  'March' => 'Maart',
  'April' => 'April',
  'May' => 'Mei',
  'June' => 'Juni',
  'July' => 'Juli',
  'August' => 'Augustus',
  'September' => 'September',
  'October' => 'Oktober',
  'November' => 'November',
  'December' => 'December',
  'Jan' => 'Jan',
  'Feb' => 'Feb',
  'Mar' => 'Mar',
  'Apr' => 'Apr',
  'May' => 'Mei',
  'Jun' => 'Jun',
  'Jul' => 'Jul',
  'Aug' => 'Aug',
  'Sep' => 'Sep',
  'Oct' => 'Okt',
  'Nov' => 'Nov',
  'Dec' => 'Dec',
  # from sendemaillib
  'Sending text only to' => 'Verzend enkel tekst naar',
  'Sending Campaign' => 'Bericht aan het verzenden',
  'with subject' => 'met onderwerp',
  'to' => 'aan',
  'Admin Authentication initialisation failure' => 'Admin Authenticatie initialisatie mislukt',
  'Your password for phplist' => 'Uw wachtwoord voor phplist',
  'Your password is' => 'Uw wahtwoord is',
  'Your password has been sent by email' => 'Uw wachtwoord is per email verzonden',
  'Unable to send the password' => 'Kan het wachtwoord niet mailen',
  'Your IP address has changed. For security reasons, please login again' => 'Uw IP-adres is gewijzigd, om veiligheidsredenen dient u opnieuw in te loggen',
  'goodbye' => 'Tot ziens',
  'good morning' => 'Goedemorgen',
  'good afternoon' => 'Goedemiddag',
  'good evening' => 'Goedenavond',
  'In safe mode, not everything will work as expected' => 'In veilige modus zal niet alles werken als verwacht',
  'Things will work better when PHP magic_quotes_gpc = on' => 'Het zal beter gaan als PHP magic_quotes_gpc = <b>on</b>',
  'Things will work better when PHP magic_quotes_runtime = off' => 'Het zal beter gaan als PHP magic_quotes_runtime = off',
  'You are trying to use RSS, but XML is not included in your PHP' => 'U probeert RSS te gebruiken, maar XML is niet ingevoegd bij uw PHP',
  'open_basedir restrictions are in effect, which may be the cause of the next warning' => 'open_basedir beperkingen zijn in werking, wat de oorzaak van de volgende waarschuwing kan zijn',
  'The attachment repository does not exist or is not writable' => 'De map voor attachments bestaat niet of is niet beschrijfbaar',
  'You are trying to use PDF support without having FPDF loaded' => 'U probeert PDF support te gebruiken zonder FPDF te hebben geladen',
  'The pageroot in your config does not match the current locationCheck your config file.' => 'De paginaroot in uw configuratie komt niet overeen met deze locatie<br/>Controleer uw configuratie bestand.',
  'Sorry this page was not found in the plugin' => 'Sorry deze pagina werd niet gevonden in de plugin',
  'Sorry not Implemented yet' => 'Sorry, nog niet geimplementeerd',
  'You do not have enough privileges to access this page' => 'U heeft niet genoeg rechten om deze pagina te betreden',
  'Sorry, help for this topic is not available yet: ' => 'Sorry, help voor dit onderwerp is nog niet aanwezig: ',
  'Close this window' => 'sluit dit venster',
  'success' => 'gelukt',
  'failed' => 'mislukt',
  'default login is' => 'Standaard login is',
  'with password' => 'Met wachtwoord',
  'Name' => 'Naam',
  'Password' => 'Wachtwoord',
  'Enter' => 'Verder',
  'forgot password' => 'Wachtwoord vergeten?',
  'enter your email' => 'Geef uw email adres',
  'send password' => 'Verzend Wachtwoord',
  'An image exists on the server, check this box to keep the existing one' => 'Een afbeelding met deze naam bestaat reeds op de server, selecteer deze box om de bestaande te houden',
  'View Image' => 'Bekijk Afbeelding',
  'Upload new image' => 'Upload nieuwe afbeelding',
  'textline' => 'tekstlijn',
  'textarea' => 'tekstveld',
  'date' => 'datum',
  'checkbox' => 'checkbox',
  'radio' => 'radio',
  'select' => 'selecteer',
  'checkboxgroup' => 'checkboxgroep',
  'unnamed list' => 'onbenaamde lijst',
  'Unknown' => 'ongekend',
  'very little time' => 'zeer weinig tijd',
  'A process for this page is already running and it was still alive' => 'Een verwerking voor deze pagina is reeds bezig en het was nog steeds bezig',
  'seconds ago' => 'seconden geleden',
  'We have been waiting too long, I guess the other process is still going ok' => 'We hebben te lang gewacht, Ik gok dat het andere process nog steeds goed draait',
  'Sleeping for 20 seconds, aborting will quit' => 'Microslaapje van 20s, Annuleren = quit',
  'No Image was found' => 'Geen afbeelding gevonden',
  'Campaigns' => 'berichten',
  'Bounces' => 'bounces',
  'bounce' => 'bounce',
  'msg' => 'ber', # as in short for message
  'time' => 'tijd',
  'sent' => 'verzonden',
  'text' => 'tekst',
  'html' => 'html',
  #
  # new for 2.9.5
  'delete user' => 'verwijder gebruiker',
  'unconfirm user' => 'de-bevestig gebruiker',
  'delete user and bounce' => 'verwijder gebruiker en bounce',
  'unconfirm user and delete bounce' => 'de-bevestig gebruiker en verwijder bounce',
  'blacklist user and delete bounce' => 'plaats gebruiker op blacklist en verwijder bounce',
  'delete bounce' => 'verwijder bounce',
  'blacklist user' => 'plaats gebruiker op blacklist',
  'manage bounces' => 'beheer bounces',
  '%' => '%',
  'invalid login from %s, tried logging in as %s' => 'ongeldige login van %s, probeerde in te loggen als %s',
  'successful password request from %s for %s' => 'succesvol wachtwoordverzoek van %s voor %s',
  'failed password request from %s for %s' => 'wachtwoordverzoek mislukt van %s voor %s',
  'login ip invalid from %s for %s (was %s)' => 'login ip ongeldig van %s voor %s (was %s)',
  'invalidated login from %s for %s (error %s)' => 'ongeldig gemaakte login van %s voor %s (fout %s)',
  'close' => 'sluit',
  'open' => 'open',
  'import is not available' => 'import is niet beschikbaar',

  # new for 2.10.0
  'Please wait, upgrading your database, do not interrupt' => 'Wacht aub, bezig met upgraden van de database, onderbreek dit niet',
  'purgerss' => 'filter rss',
  'Purge RSS items' => 'Filter RSS items',
  'In order to login, you need to enable cookies in your browser' => 'Om in te loggen moet je cookies accepteren in je browser',

  # added 2.10.2
  'Your version of PHP has a major security issue.It is best to upgrade to the latest version of PHP. Read More about this issue.' => 'Uw PHP versie heeft een belangrijk veiligheidsprobleem.<br/>U kunt best upgraden naar de nieuwste versie van PHP. <a href="http://www.hardened-php.net/globals-problem">Lees meer</a> over dit probleem.',

);

?>
