<?php

$lan = array(
  'Your database is out of date, please make sure to upgrade' => 'Ваша база данных устарела. Пожалуйста, установите более новую версию',
  'Your version' => 'Установленная версия',
  'Latest version' => 'Последняя версия',
  'phplist version' => 'Версия <a href="http://www.phplist.com">phplist</a>',
  'Database has not been initialised' => 'База данных не была инициализирована',
  'go to' => 'Перейти к',
  'Initialise Database' => 'Инициализировать',
  'to continue' => 'Для продолжения',
  'A new version of PHPlist is available!' => 'Доступна новая версия PHPlist!',
  'The new version may have fixed security issues,<br/>so it is recommended to upgrade as soon as possible' => 'Возможно, в новой версии решены проблемы с безопасностью,<br/>поэтому рекомендуется установить новую версию как можно скорее',
  'View what has changed' => 'Просмотреть изменения',
  'Download' => 'Скачать',
  'System Functions' => 'Системные функции',
  'Setup ' => 'Настройка ',
  'Check Database structure' => 'Проверить структуру базы данных',
  'View the eventlog' => 'Просмотреть лог событий',
  'Configuration functions' => 'Функции настройки',
  'Configure Attributes' => 'Настроить аттрибуты',
  'Control values for' => 'Контрольные значения для',
  'Control values for' => 'Контрольные значения для',
  'Control values for' => 'Контрольные значения для',
  'Configure Subscribe pages' => 'Настроить страницы подписки',
  'List and user functions' => 'Функции пользователей и списков',
  'List the current lists' => 'Показать текущие списки',
  'List all Users' => 'Показать всех пользователей',
  'Reconcile the user database' => 'Синхронизировать базу данных с пользователями',
  'Import Users' => 'Импорт пользователей',
  'Export Users' => 'Экспорт пользователей',
  'Administrator functions' => 'Функции администратора',
  'Add, edit and remove Administrators' => 'Добавление, изменение и удаление администраторов',
  'Configure attributes for administrators' => 'Настроить аттрибуты администраторов',
  'Message functions' => 'Фукции сообщений',
  'Configure Templates' => 'Настроить шаблоны',
  'List all Messages' => 'Показать все сообщения',
  'Process the Message queue' => 'Обработать очередь сообщений',
  'RSS Functions' => 'Функции RSS',
  'Get RSS feeds' => 'Получить RSS-ленты',
  'View RSS items' => 'Просмотреть элементы RSS',
  'Plugins' => 'Плагины',
  'Upgrade' => 'Обновление',
'Change your details (e.g. password)' => 'Поменять собственные детали (напр. пароль)',
'You have set TEST in config.php to 1, so it will only show what would be sent' => 'Вы поставили значение TEST в файле config.php равному 1, поэтому будет показано, только то, что будет послано',

  # added at a later stage
  'setup' => 'настройка',
  'upgrade' => 'обновление',
  'dbcheck' => 'проверка бд',
  'eventlog' => 'лог событий',
  'attributes' => 'аттрибуты',
  'spage' => 'страницы подписки',
  'list' => 'списки',
  'reconcileusers' => 'синхронизация пользователей',
  'import' => 'импорт',
  'export' => 'экспорт',
  'admins' => 'администраторы',
  'adminattributes' => 'аттрибуты администраторов',
  'send' => 'отправить',
  'templates' => 'шаблоны',
  'processqueue' => 'обработать очередь сообщений',
  'processbounces' => 'обработать отказы',
  'getrss' => 'получить rss',
  'viewrss' => 'просмотр rss',
  'admin' => 'администратор',
  'preparesend' => 'подготовить и отправить',
  'sendprepared' => 'отправить подготовленное',


);

?>