<?php
$lan = array (
  'Email is a system attribute' => 'Email是系統欄位',
  'Converting' => '轉換中',
  'from' => '從',
  'to' => '到',
  'deleting' => '刪除中',
  'Cannot delete attribute, it is being used by the following forms:' => '無法刪除欄位，目前被下面表單使用：',
  'Warning, changing types of attributes can take a long time' => '注意，修改任何類型的欄位都可能需要等候一段時間',
  'Sorry, merging of checkbox groups is not implemented yet' => '抱歉，合併選取方塊群組還沒完成',
  'cannot merge just one attribute' => '無法只合併一個欄位',
  'Merging' => '合併中',
  'into' => '變成',
  'Can only merge attributes of the same type' => '只能夠合併同樣類型的欄位',
  'Existing attributes' => '已存在的欄位',
  'No Attributes have been defined yet' => '還沒定義任何欄位',
  'Load data from' => '讀取資料自',
  'predefined defaults' => '預設值',
  'Attribute' => '欄位',
  'used in' => '使用於',
  'forms' => '表單',
  'tag' => '標籤',
  'name' => '名稱',
  'Type' => '類型',
  'Default Value' => '預設值',
  'Order of Listing' => '順序',
  'Is this attribute required?' => '必填？',
  'textline' => '文字方塊',
  'checkbox' => '核選方塊',
  'checkboxgroup' => '核選方塊群組',
  'radio' => '單選項目',
  'select' => '下拉選單',
  'hidden' => '隱藏項目',
  'textarea' => '多行文字',
  'date' => '日期',
  'savechanges' => '儲存',
  'With TAGGED attributes' => '使用標示的欄位',
  'delete' => '刪除',
  'Merge' => '合併',
  'Add new Attribute' => '新增欄位',

);
?>