<?php
$lan = array (
  'No such record' => '沒有記錄',
  'Back to the list of bounces' => '回到退信清單',
  'Not Found' => '找不到<br/>',
  'Added %s to bouncecount for subscriber %s' => '新增 %s 到 %s 的退信指數<br/>',
  'Could not add %s to bouncecount for subscriber %s' => '無法新增 %s 到 %s 的退信指數<br/>',
  'Made subscriber %s unconfirmed' => '讓使用者 %s 狀態變成未確認<br/>',
  'Made subscriber %s to receive text' => '讓使用者 %s 訂閱純文字版本<br/>',
  'Deleted subscriber %s' => '刪除使用者 %s<br/>',
  'Deleting bounce %s .. ' => '刪除退信中 %s ..',
  '..Done, loading next bounce..' => '..完成，讀取下一封退信..',
  'No such Record' => '沒有這筆記錄',
  'Possible Actions:' => '動作：',
  'For subscriber with email' => '給使用者信箱',
  'Increase bouncecount with' => '增加退信指數於',
  '(use negative numbers to decrease)' => '(使用負數來減少)',
  'Mark subscriber as unconfirmed' => '讓使用者狀態變成未確認',
  '(so you can resend the request for confirmation)' => '(接著您就可以重新寄送確認信函)',
  'Set subscriber to receive text instead of HTML' => '設定使用者訂閱純文字版本',
  'Delete subscriber' => '刪除使用者',
  'Delete this bounce and go to the next' => '刪除這封退信並且讀取下一封',
  'Do the above' => '執行',
  'Bounce Details:' => '退信細節：',
  'ID' => 'ID',
  'Date' => '日期',
  'Status' => '狀態',
  'Comment' => '意見',
  'Header' => '頁首',
  'Body' => '內容',
  'Regular Expression' => '樣式比對',
  'Action' => '操作',
  'Memo for this rule' => '這個規則的備註',
  'Add new Rule' => '新增規則',
  'Create New Rule based on this bounce' => '以這封退信建立新規則',

);
?>