<?php
$lan = array (
  'noaccess' => '沒有這個電子報，或是您沒有存取的權限',
  'Warning: You indicated the content was not HTML, but there were  some HTML  tags in it. This  may  cause  errors' => '警告：您指定電子報內容不是HTML，但是內容包含了一些 HTML 標籤，這可能導致一些問題發生',
  'Adding' => '新增中',
  'Mime Type is longer than 255 characters, this is trouble' => 'Mime 類型超過 255 個字元，這會產生問題',
  'Added attachment ' => '加入的附加檔案',
  'Uploaded file not properly received, empty file' => '上傳檔案失敗，檔案是空的',
  'Message saved' => '電子報儲存了',
  'Message added' => '電子報新增了',
  'Message queued for send' => '電子報已經加入佇列',
  'processqueue' => '處理電子報佇列',
  'Sorry, you used invalid characters in the Subject field.' => '抱歉，標題欄位包含了錯誤字元',
  'Sorry, you used invalid characters in the From field.' => '抱歉，寄件人欄位包含了錯誤字元',
  'Please enter a from line.' => '請輸入寄件人',
  'Please enter a message' => '請輸入內容',
  'Please enter a subject' => '請輸入主旨',
  'Error: you can use an attribute in one rule only' => '錯誤：在一個規則中只能夠使用一個欄位',
  'Please select the list(s) to send the campaign to' => '請選擇要寄送的電子報群組',
  'No target email addresses listed for testing.' => '沒有測試用的電子郵件位址',
  'Email address not found to send test message.' => '找不到電子郵件位址來寄送測試電子報',
  'Sent test mail to' => '送出測試郵件到',
  'Removed Attachment ' => '移除的附加檔案',
  'Existing criteria' => '已經存在的規則',
  'Remove' => '移除',
  'Calculating' => '計算中',
  'Calculate' => '計算',
  'Content' => '內容',
  'Format' => '格式',
  'Attach' => '附加',
  'Scheduling' => '排程中',
  'Criteria' => '規則',
  'lists' => '電子報',
  'Warning, You have unsaved changes
Click OK to continue, or Cancel to stay on this page
so you can save the changes.' => '警告，您還沒儲存異動n請先儲存，或是點選取消來忽略異動',
  'What is prepare a message' => '什麼是撰寫草稿',
  'subject' => '主旨',
  'From Line' => '寄件人',
  'Embargoed Until' => '停止寄送直到',
  'Repeat campaign every' => '重複寄送於每個',
  'no repetition' => '不重複',
  'Hour' => '時',
  'Day' => '天',
  'Week' => '週',
  'Repeat Until' => '重複至',
  'Auto Detect' => '自動偵測',
  'Send As' => '另外寄出',
  'html' => 'HTML',
  'text' => '純文字',
  'PDF' => 'PDF',
//  'text and html' => '純文字與HTML', //obsolete by bug 0009687//obsolete by bug 0009687
  'Text and PDF' => '純文字與PDF',
  'Use Template' => '使用樣版',
  'select one' => '選擇一個',
  'If you want to use this message as the template for sending RSS feeds     select the frequency it should be used for and use [RSS] in your message to indicate where the list of items needs to go.' => '如果您使用這個電子報作為寄送RSS資訊的樣版，請透過使用[RSS]的頻率來決定要在電子報中加入多少個項目',
  'none' => '無',
  'message' => '電子報',
  'expand' => '展開',
  'Plain text version of message' => '純文字格式電子報',
  'Footer' => '電子報頁底',
  'Use [UNSUBSCRIBE] to insert the personal unsubscribe URL for each user.   Use [PREFERENCES] to insert the personal URL for a user to update their details.' => '使用 <b>[UNSUBSCRIBE]</b> 來加入訂閱者個人的取消訂閱網址
    <br/>使用 <b>[PREFERENCES]</b> 來加入訂閱者修改個人資料的網址',
  'Add attachments to your campaign' => '新增附加檔案',
  'The upload has the following limits set by the server' => '上傳檔案有下面限制',
  'Maximum size of total data being sent to the server' => '總資料量上限',
  'Maximum size of each individual file' => '單一檔案大小上限',
  'Current Attachments' => '目前的附加檔案',
  'filename' => '檔案名稱',
  'desc' => '說明',
  'size' => '大小',
  'file' => '檔案',
  'del' => '刪除',
  'New Attachment' => '新增附加檔案',
  'Add (and save)' => '新增(儲存)',
  'Path to file on server' => '伺服器上的檔案路徑',
  'Description of attachment' => '附加檔案說明',
  'Delete Checked' => '刪除選取的',
  'Send Test Message' => '寄送測試電子報',
  ' to email address(es)' => ' 到郵件位址',
  '(comma separated addresses - all must be users)' => '(用半形的逗點分隔電子郵件)',
  '         Select the criteria for this message:                  to use a criteria, check the box next to it         then check the radio button next to the attribute you want to use         then choose the values of the attributes you want to send the message to         Note: Messages will be sent to people who fit to Criteria 1 AND Criteria 2 etc                   ' => '        <p><b>選擇這個電子報的規則：</b>
        <ol>
        <li>要使用一個規則，請勾選旁邊的方塊
        <li>接著勾選您希望使用的欄位
        <li>接著選擇符合規則的欄位值
        <i>注意：</i> 電子報將會寄送到符合 <i>規則 1</i> <b>與</b> <i>規則 2</i>等使用者',
  'Criterion' => '標準',
  'Use this one' => '使用這個',
  'or' => '或',
  'is' => '是',
  'isnot' => '不是',
  'isbefore' => '在之前',
  'isafter' => '在之後',
  'There are currently no attributes available to use for sending. The campaign will go to any user on the lists selected' => '目前沒有任何欄位，電子報會寄給所有訂閱人',
  'checked' => '勾選了',
  'unchecked' => '未勾選',
  'buggywithie' => '注意，這個功能在IE中可能會發生問題n建議您使用 Mozilla, Firefox 或是 Operan在設定檔案中關閉 STACKED_ATTRIBUTE_SELECTION 項目',
  'matchallrules' => '符合所有規則',
  'matchanyrules' => '符合任何規則',
  'addcriterion' => '新增規則',
  'Save as Draft' => '存成草稿',
  'savechanges' => '儲存異動',
  'selectattribute' => '選擇欄位',
  'dd-mm-yyyy' => 'yyyy-mm-dd',
  'Please select the lists you want to send it to' => '請選擇要寄送的電子報群組',
  'alllists' => '所有電子報群組',
  'listactive' => '啟用中的電子報群組',
  'listnotactive' => '停用中的電子報群組',
  'Select the lists to be excluded.' => '選擇排除的電子報群組',
  'The campaign will go to users who are a member of the lists above,     unless they are a member of one of the lists you select here.' => '這個電子報將會寄送給任何訂閱這些電子報群組的使用者',
  'Sorry, there are currently no lists available' => '抱歉，目前沒有任何電子報群組',
  'Send Campaign' => '寄送電子報到選擇的通訊論壇',
  'You are trying to send a remote URL, but PEAR::HTTP_Request is not available, so this will fail' => '您正嘗試寄送到一個遠端網址，但是 PEAR::HTTP/Request 外掛不存在，所以無法執行',
  'Misc' => '其他',
  'email to alert when sending of this message starts' => '這封信開始寄送時發送訊息提醒',
  'email to alert when sending of this message has finished' => '這封信完成寄送時發送訊息提醒',
  'separate multiple with a comma' => '多個項目請用逗點分隔',
  'operator' => '操作元',
  'values' => '數值',
  '%d users apply' => '%d 個使用者',
  'reload' => '重新讀取',

);
?>