<?php 
$lan = array(

  'add_list' => 'Tilf&oslash;j liste', //duplicated in import1_text
  'cannot connect to remote database' => 'kan ikke forbinde til remote database',
  'No users to copy, is the prefix correct?' => 'Ingen brugere at kopiere, er pr&aelig;fikset korrekt?',
  'Please enter details of the remote Server' => 'Venligst indtast info om remote server',
  'Server:' => 'Server:',
  'user' => 'Bruger:',
  'Password:' => 'Kodeord:',
  'Database Name:' => 'Database navn:',
  'Table prefix:' => 'Tabel pr&aelig;efiks:',
  'Usertable prefix:' => 'Brugertabel pr&aelig;fiks:',
  'select_lists' => 'V&aelig;lg den liste, der skal tilf&oslash;jes emails til',
  'Copy lists from remote server (lists are matched by name)' => 'Kopier lister fra remote server (lister matches efter navn)',
  'Mark new users as HTML:' => 'Marker nye brugere som HTML:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'Hvis du v&aelig;lger "Overskriv eksisterende", vil information om en bruger blive erstattet af den importerede information. Brugere matches efter email.',
  'Overwrite Existing:' => 'Overskriv eksisterende:',
  'Making connection with remote database' => 'Opretter forbindelse til remote database',
  'Getting data from ' => 'Henter data fra ',
  'Remote version is' => 'Remote version er',
  'Remote version has' => 'Remote version har',
  'users' => 'brugere',
  'lists' => 'lister',
  'Copying lists' => 'Kopierer lister',
  'list' => 'Liste',
  'exists locally' => 'findes lokalt',
  'created locally' => 'oprettet lokalt',
  'Remote list' => 'Remote liste',
  'not created' => 'ikke oprettet',
  'Copying attributes' => 'Kopierer attributter',
  'Attribute' => 'Attribut',
  'Copying users' => 'Kopierer brugere',
  'overwriting local data' => 'overskriver lokal data',
  'keeping local data' => 'bevarer lokal data',
  'is a new user' => 'er ny bruger',
  'Error, no mapped attribute for' => 'Fejl, ingen attribut mappet til',
  'Error, no local list defined for' => 'Fejl, ingen lokal liste defineret til',
  'No lists available' => 'Ingen lister tilg&aelig;ngelige',
  'Done' => 'Udf&oslash;rt',
  'new users' => 'nye brugere',
  'and' => 'og',
  'existing users' => 'eksisterende brugere',
  'continue' => 'Forts&aelig;t',

);
?>