<?php
$lan = array(

  'add_list' => 'Lijst toevoegen', //duplicated in import1_text
  'cannot connect to remote database' => 'kan geen verbinding maken met de database',
  'No users to copy, is the prefix correct?' => 'Geen gebruikers te kopieren, is de prefix juist?',
  'Please enter details of the remote Server' => 'Geef aub de details van de Server',
  'Server:' => 'Server:',
  'user' => 'Gebruiker:',
  'Password:' => 'Wachtwoord:',
  'Database Name:' => 'Database Naam:',
  'Table prefix:' => 'Tabel prefix:',
  'Usertable prefix:' => 'Gebruikerstabel prefix:',
  'select_lists' => 'Selecteer de lijst waar de email in moeten komen',
  'Copy lists from remote server (lists are matched by name)' => 'Kopieer de lijst van de server (lijsten komen overeen per naam)',
  'Mark new users as HTML:' => 'Markeen nieuwe gebruiker als HTML:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'Als u "Overschrijf Bestaand" aanvinkt, dan zal de info van een gerbuiker worden vervangen door de geimporteerde info. Gebruikers komen overeen per email.',
  'Overwrite Existing:' => 'Overschrijf Bestaand:',
  'Making connection with remote database' => 'Maak verbinding met de database op afstand',
  'Getting data from ' => 'Ontvangen van data van ',
  'Remote version is' => 'Versie op afstand is',
  'Remote version has' => 'Versie op afstand heeft',
  'users' => 'gebruikers',
  'lists' => 'lijsten',
  'Copying lists' => 'Lijsten Kopieren',
  'list' => 'Lijst',
  'exists locally' => 'Bestaat al lokaal',
  'created locally' => 'Lokaal aangemaakt',
  'Remote list' => 'Lijst op afstand',
  'not created' => 'niet aangemaakt',
  'Copying attributes' => 'Attributen kopieren',
  'Attribute' => 'Attribuut',
  'Copying users' => 'Gebruikers Kopieren',
  'overwriting local data' => 'overschrijven van locale data',
  'keeping local data' => 'behouden van locale data',
  'is a new user' => 'is een nieuwe gebruiker',
  'Error, no mapped attribute for' => 'Fout, geen in kaart gebrachte attributen voor',
  'Error, no local list defined for' => 'Fout, Geen locale lijst gedefinieerd voor',
  'No lists available' => 'Geen lijsten beschikbaar',
  'Done' => 'Klaar',
  'new users' => 'nieuwe gebruikers',
  'and' => 'en',
  'existing users' => 'bestaande gebruikers',
  'continue' => 'Ga verder',

);
?>