<?php 
$lan = array(

  'add_list' => 'Add a list', //duplicated in import1_text
  'cannot connect to remote database' => 'cannot connect to remote database',
  'No users to copy, is the prefix correct?' => 'No users to copy, is the prefix correct?',
  'Please enter details of the remote Server' => 'Please enter details of the remote Server',
  'Server:' => 'Server:',
  'user' => 'User:',
  'Password:' => 'Password:',
  'Database Name:' => 'Database Name:',
  'Table prefix:' => 'Table prefix:',
  'Usertable prefix:' => 'Usertable prefix:',
  'select_lists' => 'Select the lists to add the emails to',
  'Copy lists from remote server (lists are matched by name)' => 'Copy lists from remote server (lists are matched by name)',
  'Mark new users as HTML:' => 'Mark new users as HTML:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.',
  'Overwrite Existing:' => 'Overwrite Existing:',
  'Making connection with remote database' => 'Making connection with remote database',
  'Getting data from ' => 'Getting data from ',
  'Remote version is' => 'Remote version is',
  'Remote version has' => 'Remote version has',
  'users' => 'users',
  'lists' => 'lists',
  'Copying lists' => 'Copying lists',
  'list' => 'List',
  'exists locally' => 'exists locally',
  'created locally' => 'created locally',
  'Remote list' => 'Remote list',
  'not created' => 'not created',
  'Copying attributes' => 'Copying attributes',
  'Attribute' => 'Attribute',
  'Copying users' => 'Copying users',
  'overwriting local data' => 'overwriting local data',
  'keeping local data' => 'keeping local data',
  'is a new user' => 'is a new user',
  'Error, no mapped attribute for' => 'Error, no mapped attribute for',
  'Error, no local list defined for' => 'Error, no local list defined for',
  'No lists available' => 'No lists available',
  'Done' => 'Done',
  'new users' => 'new users',
  'and' => 'and',
  'existing users' => 'existing users',
  'continue' => 'Continue',

);
?>