<?php 
$lan = array(

  'add_list' => 'Lista hozzáadása', //duplicated in import1_text
  'cannot connect to remote database' => 'nem lehet csatlakozni a távoli adatbázishoz',
  'No users to copy, is the prefix correct?' => 'Nincs másolandó felhasználó, jó az előtag?',
  'Please enter details of the remote Server' => 'Írja be a távoli kiszolgáló adatait',
  'Server:' => 'Kiszolgáló:',
  'user' => 'Felhasználónév:',
  'Password:' => 'Jelszó:',
  'Database Name:' => 'Adatbázis neve:',
  'Table prefix:' => 'Táblanév előtag:',
  'Usertable prefix:' => 'Felhasználó-táblanév előtag:',
  'select_lists' => 'Jelölje be azokat a listákat, melyekhez hozzá akarja adni az e-mail címeket',
  'Copy lists from remote server (lists are matched by name)' => 'Listák másolása távoli kiszolgálóról (a listák egyeztetése név alapján)',
  'Mark new users as HTML:' => 'Az új felhasználók megjelölése HTML-ként:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'Ha bejelöli a "Meglévők felülírása" beállítást, akkor a felhasználó adatbázisban lévő adatai lecserélésre kerülnek az importált adatokkal. A felhasználók egyeztetése az e-mail cím alapján történik.',
  'Overwrite Existing:' => 'Meglévők felülírása:',
  'Making connection with remote database' => 'Csatlakozás a távoli adatbázishoz',
  'Getting data from ' => 'Adatok lekérése innen: ',
  'Remote version is' => 'A távoli változat',
  'Remote version has' => 'A távoli verziónak van',
  'users' => 'felhasználók',
  'lists' => 'listák',
  'Copying lists' => 'Listák másolása',
  'list' => 'Lista',
  'exists locally' => 'helyileg létezik',
  'created locally' => 'helyben létrehozva',
  'Remote list' => 'Távoli lista',
  'not created' => 'nincs létrehozva',
  'Copying attributes' => 'Tulajdonságok másolása',
  'Attribute' => 'Tulajdonság',
  'Copying users' => 'Felhasználók másolása',
  'overwriting local data' => 'a helyi adatok felülírása',
  'keeping local data' => 'a helyi adatok megőrzése',
  'is a new user' => 'egy új felhasználó',
  'Error, no mapped attribute for' => 'Hiba: Nincs egyeztetett tulajdonság a következőhöz:',
  'Error, no local list defined for' => 'Hiba: Nincs helyi lista meghatározva a következőhöz:',
  'No lists available' => 'Nincsenek listák',
  'Done' => 'Kész',
  'new users' => 'új felhasználók',
  'and' => 'és',
  'existing users' => 'létező felhasználók',
  'continue' => 'Folytatás',

);
?>