<?php 
$lan = array(
  'import is not available' => 'importa&ccedil;&atilde;o n&atilde;o est&aacute; dispon&iacute;vel',
  'add_list' => 'Adicionar uma lista', //duplicada em import1_text
  'cannot connect to remote database' => 'n&atilde;o foi poss&iacute;vel conectar &agrave; base de dados',
  'No users to copy, is the prefix correct?' => 'Nenhum usu&aacute;rio a ser copiado, o prefixo est&aacute; correto?',
  'Please enter details of the remote Server' => 'Por favor, insira os dados do Servidor remoto',
  'Server:' => 'Servidor:',
  'user' => 'Usu&aacute;rio:',
  'Password:' => 'Senha:',
  'Database Name:' => 'Nome da Base de Dados:',
  'Table prefix:' => 'Prefixo da tabela:',
  'Usertable prefix:' => 'Prefixo da tabela de usu&aacute;rios:',
  'select_lists' => 'Selecione as listas nas quais voc&ecirc; quer adicionar os emails',
  'Copy lists from remote server (lists are matched by name)' => 'Copiar listas do servidor local (as listas s&atilde;o encontradas atrav&eacute;s do nome)',
  'Mark new users as HTML:' => 'Marcar novos usu&aacute;rios como HTML:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'Se voc&ecirc; marcar "Sobrescrever Existente", a informa&ccedil;&atilde;o do usu&aacute;rio na base de dados ser&aacute; substitu&iacute;da pela informa&ccedil;&atilde;o importada. Os usu&aacute;rios s&atilde;o encontrados atrav&eacute;s do email.',
  'Overwrite Existing:' => 'Sobrescrever existente:',
  'Making connection with remote database' => 'Conectando com a base de dados remota',
  'Getting data from ' => 'Obtendo dados de ',
  'Remote version is' => 'A vers&atilde;o remota &eacute;',
  'Remote version has' => 'A vers&atilde;o remota tem',
  'users' => 'usu&aacute;rios',
  'lists' => 'listas',
  'Copying lists' => 'Copiando listas',
  'list' => 'Lista',
  'exists locally' => 'j&aacute; existe',
  'created locally' => 'localmente criada',
  'Remote list' => 'Lista remota',
  'not created' => 'n&atilde;o criado',
  'Copying attributes' => 'Copiando atributos',
  'Attribute' => 'Atributo',
  'Copying users' => 'Copiando usu&aacute;rios',
  'overwriting local data' => 'sobrescrevendo dados locais',
  'keeping local data' => 'mantendo dados locais',
  'is a new user' => '&eacute; um novo usu&aacute;rio',
  'Error, no mapped attribute for' => 'Erro: n&atilde;o h&aacute; atributos mapeados para',
  'Error, no local list defined for' => 'Erro, nenhuma lista local definida para',
  'No lists available' => 'Nenhuma lista dispon&iacute;vel',
  'Done' => 'Conclu&iacute;do',
  'new users' => 'novos usu&aacute;rios',
  'and' => 'e',
  'existing users' => 'usu&aacute;rio existentes',
  'continue' => 'Continuar',

);
?>
