<?php 
$lan = array(
  "NoRecord" => "Il record non esiste",
  "BackToBList" => "Torna alla lista dei messaggi respinti",
  "NotFound" => "Non trovato",
  "AddedToB" => "Aggiunto %s al conto del numero di respinte per l'utente %s",
  "NotAddedToB" => "Non posso aggiungere %s al conto del numero di respinte per l'utente %s<br/>",
  "MadeUnconfirmed" => "Imposta l'utente %s come \"Non confermato\"<br/>",
  "MadeUserRText" => "Abilita l'utente %s a ricevere testo<br/>",
  "DelUser" => "Cancella l'utente %s<br/>",
  "DeletingB" => "Sto eliminando il messaggio respinto %s...",
  "DoneAndLoading" => "Fatto, carico il prossimo messaggio respinto...",
  "NoSRecord" => "Questo record non esiste",
  "PossibleActions" => "Possibili Azioni:",
  "ForUser" => "Per l'utente con email",
  "IncreaseB" => "Aumenta il conto delle respinte di",
  "IncreaseBNote" => "(usa numeri negativi per diminuire)",
  "MarkAsUnconfirmed" => "Segna l'utente come \"Non confermato\"",
  "MarkAsUnconfirmedNote" => "(cos&igrave; puoi reinviare la richiesta di conferma)",
  "SetReceiveText" => "Abilita l'utente a ricevere solo testo invece di HTML",
  "DelUser1" => "Elimina utente",
  "DelAndGo" => "Elimina questo messaggio respinto e vai al successivo",
  "DoAbove" => "Fai quanto specificato",
  "BounceDetails" => "Dettagli messaggio respinto:",
  "ID" => "ID",
  "Date" => "Data",
  "Status" => "Stato",
  "Comment" => "Commento",
  "Header" => "Intestazione",
  "Body" => "Corpo",
  # new in 2.9.5
  'Regular Expression' => 'Espressione Regolare',
  'Action' => 'Azione',
  'Memo for this rule' => 'Memorizza questa regola',
  'Add new Rule' => 'Aggiungi una nuova regola',
  'Create New Rule based on this bounce' => 'Crea una nuova regola basata su questo messaggio respinto',
);
?>