<?php
$lan = array(
  'Number of %s rules: %d' => 'Numero di %s regole: %d',
  'active' => 'attivo',
  'candidate' => 'candidato',
  'Bounce Regular Expressions' => 'Espressioni regolari per i messaggi respinti',
  'rule' => 'regola',
  'expression' => 'espressione',
  'action' => 'azione',
  '#bncs' => '#bncs',
  'tag' => 'seleziona',
  'order' => 'ordina',
  'del' => 'elimina',
  'with tagged rules: ' => 'con regole selezionate: ',
  'delete' => 'elimina',
  'make inactive' => 'rendi inattive',
  'Save Changes' => 'Salva le modifiche',
  'add a new rule' => 'aggiungi una nuova regola',
  'Regular Expression' => 'Espressione regolare',
  'Memo for this rule' => 'Memo per questa regola',
  'Add new Rule' => 'Aggiungi una nuova regola',
  'make active' => 'attiva',
  'No Rules found' => 'Regole non trovate',
  'match' => 'abbina',
  'That rule exists already' => 'Questa regola esiste gi&agrave;',
);
?>
