<?php
# file with common texts for translation
$lan = array(
  'Logout' => 'Esci',
  'Main Page' => 'Pagina Principale',
  'Subscriber' => 'Utente',
  'Error' => 'Errore',
  'version' => 'Versione',
  'powered by' => 'Creato con',
  'Fatal Error' => 'Errore irreversibile',
  'Warning' => 'Attenzione',
  'Information' => 'Informazioni',
  'help' => 'Aiuto',
  'about' => 'Informazioni su',
  'lists' => 'Liste',
  'send a message' => 'Invia un messaggio',
  'Subscribers' => 'utenti',
  'manage users' => 'Gestione utenti',
  'Campaigns' => 'Messaggi',
  'statistics' => 'Statistiche',
  'process queue' => 'Elabora la coda',
  'configure' => 'Configura',
  'Subscribe Pages' => 'Pagine di iscrizione',
  'Send a prepared message' => 'Invia un messaggio preparato',
  'Prepare a message' => 'Prepara un messaggio',
  'Templates' => 'Modelli',
  'View Bounces' => 'Visualizza messaggi respinti',
  'Process Bounces' => 'Recupera messaggi respinti',
  'Eventlog' => 'Log eventi',
  'Sunday' => 'Domenica',
  'Monday' => 'Luned&igrave;',
  'Tuesday' => 'Marted&igrave;',
  'Wednesday' => 'Mercoled&igrave;',
  'Thursday' => 'Gioved&igrave;',
  'Friday' => 'Venerd&igrave;',
  'Saturday' => 'Sabato',
  'January' => 'Gennaio',
  'February' => 'Febbraio',
  'March' => 'Marzo',
  'April' => 'Aprile',
  'May' => 'Maggio',
  'June' => 'Giugno',
  'July' => 'Luglio',
  'August' => 'Agosto',
  'September' => 'Settembre',
  'October' => 'Ottobre',
  'November' => 'Novembre',
  'December' => 'Dicembre',
  'Jan' => 'Gen',
  'Feb' => 'Feb',
  'Mar' => 'Mar',
  'Apr' => 'Apr',
  'May' => 'Mag',
  'Jun' => 'Giu',
  'Jul' => 'Lug',
  'Aug' => 'Ago',
  'Sep' => 'Set',
  'Oct' => 'Ott',
  'Nov' => 'Nov',
  'Dec' => 'Dic',
  # from sendemaillib
  'Sending text only to' => 'Invia testo solo a',
  'Sending Campaign' => 'Invio messaggi',
  'with subject' => 'Con oggetto',
  'to' => 'a',
  'Admin Authentication initialisation failure' => 'Inizializzazione autenticazione amministratore fallita',
  'Your password for phplist' => 'La tua password per phplist',
  'Your password is' => 'La tua password &egrave;',
  'Your password has been sent by email' => 'La tua password &egrave; stata spedita via email',
  'Unable to send the password' => 'Impossibile spedire la password',
  'Your IP address has changed. For security reasons, please login again' => 'Il tuo indirizzo IP &egrave; cambiato. Per ragioni di sicurezza, ricollegati',
  'goodbye' => 'Arrivederci',
  'good morning' => 'Buongiorno',
  'good afternoon' => 'Buon pomeriggio',
  'good evening' => 'Buona sera',
  'In safe mode, not everything will work as expected' => 'In modalit&agrave; sicura (safe mode), non tutto funziona come ci si aspetterebbe',
  'Things will work better when PHP magic_quotes_gpc = on' => 'Le cose funzionano meglio se PHP magic_quotes_gpc = <b>on</b>',
  'Things will work better when PHP magic_quotes_runtime = off' => 'Le cose funzionano meglio se PHP magic_quotes_runtime = off',
  'You are trying to use RSS, but XML is not included in your PHP' => 'Stai provando a usare RSS, ma l\'estensione XML non &egrave; inclusa nel tuo PHP',
  'open_basedir restrictions are in effect, which may be the cause of the next warning' => 'Restizioni basate open_basedir sono attive, cosa che potrebbe essere causa di successivi avvisi',
  'The attachment repository does not exist or is not writable' => 'La cartella per gli allegati non esiste o non &egrave; scrivibile',
  'You are trying to use PDF support without having FPDF loaded' => 'Stai provando ad utilizzare il supporto PDF ma non &egrave; caricato FPDF',
  'The pageroot in your config does not match the current locationCheck your config file.' => 'La pageroot nella tua configurazione non corrisponde con la corrente posizione.<br/>Controlla il file di configurazione.',
  'Sorry this page was not found in the plugin' => 'La pagina non &egrave; stata trovata nei plugin',
  'Sorry not Implemented yet' => 'Funzione non ancora implementata',
  'You do not have enough privileges to access this page' => 'Non hai sufficienti privilegi per accedere a questa pagina',
  'Sorry, help for this topic is not available yet: ' => 'Non &egrave; ancora presente una pagina di aiuto per questo argomento: ',
  'Close this window' => 'Chiudi questa finestra',
  'success' => 'successo',
  'failed' => 'fallito',
  'default login is' => 'Il login predefinito &egrave;',
  'with password' => 'con password',
  'Name' => 'Nome',
  'Password' => 'Password',
  'Enter' => 'Invio',
  'forgot password' => 'Password dimenticata?',
  'enter your email' => 'Inserisci la tua email',
  'send password' => 'Invia Password',
  'An image exists on the server, check this box to keep the existing one' => 'Esiste gi&agrave; una immagine sul server, spunta questo box per conservare quella esistente',
  'View Image' => 'Visualizza immagine',
  'Upload new image' => 'Carica una nuove immagine',
  'textline' => 'linea di testo',
  'textarea' => 'area di testo',
  'date' => 'data',
  'checkbox' => 'casella di spunta',
  'radio' => 'radio button',
  'select' => 'men&ugrave; di selezione',
  'checkboxgroup' => 'gruppo di caselle di spunta',
  'unnamed list' => 'Lista anonima',
  'Unknown' => 'Sconosciuto',
  'very little time' => 'Tempo piccolissimo',
  'A process for this page is already running and it was still alive' => 'Un processo per questa pagina &egrave; attualmente attivo ed ancora in esecuzione',
  'seconds ago' => 'secondi passati',
  'We have been waiting too long, I guess the other process is still going ok' => 'Abbiamo aspettato anche troppo, suppongo vi sia un altro processo ancora in esecuzione',
  'Sleeping for 20 seconds, aborting will quit' => 'In attesa per 20 secondi, annullando sar&agrave; interrotto il processo',
  'No Image was found' => 'Nessuna immagine trovata',
  'Campaigns' => 'Messaggi',
  'Bounces' => 'Messaggi respinti',
  'bounce' => 'messaggio respinto',
  'msg' => 'msg', # as in short for message
  'time' => 'ora',
  'sent' => 'inviato',
  'text' => 'testo',
  'html' => 'html',
# new for 2.9.5
  'delete user' => 'cancella utente',
  'unconfirm user' => 'utente non confermato',
  'delete user and bounce' => 'cancella utente e messaggio respinto',
  'unconfirm user and delete bounce' => 'non confermare utente e cancella messaggio respinto',
  'blacklist user and delete bounce' => 'metti utente nella lista nera e cancella messaggio respinto',
  'delete bounce' => 'cancella messaggio respinto',
  'blacklist user' => 'utenti in blacklist',
  'manage bounces' => 'Gestisci i messaggi respinti',
  '%' => '%',
  'invalid login from %s, tried logging in as %s' => 'login non valido da %s, ha tentato di connettersi come %s',
  'successful password request from %s for %s' => 'richiesta password completata con successo da %s per %s',
  'failed password request from %s for %s' => 'richiesta password fallita da %s per %s',
  'login ip invalid from %s for %s (was %s)' => 'indirizzo IP non valido per il collegamento da %s per %s (era %s)',
  'invalidated login from %s for %s (error %s)' => 'login invalidato da %s per %s (errore %s)',
  'close' => 'chiudi',
  'open' => 'apri',
  'import is not available' => 'importazione non disponibile',
# new for 2.10.0
  'Please wait, upgrading your database, do not interrupt' => 'Si prega di attendere, aggiornamento database in corso, non interrompere',
  'purgerss' => 'Elimina RSS',
  'Purge RSS items' => 'Elimina oggetti RSS',
  'In order to login, you need to enable cookies in your browser' => 'Per effettuare l\'accesso, devi abilitare i cookies nel tuo browser',
# added 2.10.2
  'Your version of PHP has a major security issue.It is best to upgrade to the latest version of PHP. Read More about this issue.' => 'La tua versione di PHP &egrave; a rischio sicurezza.<br/>&Egrave; consigliato aggiornarlo all\'ultima versione. <a href="http://www.hardened-php.net/globals-problem">Leggi...</a> informazioni sui problemi.',
# added 2.10.4
# note to translators, this is part of a plain text email, so do not use html
  '  -------------------------------------------------------------------------------- This is a notification of a possible spam attack to your phplist subscribe page. The data submitted has been copied below, so you can check whether this was actually the case. The submitted data has been converted into non-html characters, for security reasons.  If you want to stop receiving this message, set     define("NOTIFY_SPAM",0);  in your phplist config file.  This subscriber has not been added to the database. If there is an error, you will need to  add them manually.  --------------------------------------------------------------------------------  ' => '

--------------------------------------------------------------------------------
This is a notification of a possible spam attack to your phplist subscribe page.
The data submitted has been copied below, so you can check whether this was actually the case.
The submitted data has been converted into non-html characters, for security reasons.

If you want to stop receiving this message, set 

  define(\'NOTIFY_SPAM\',0);

in your phplist config file.

This user has not been added to the database. If there is an error, you will need to 
add them manually. 
--------------------------------------------------------------------------------

',
);
?>
