<?php
$lan = array(
'The temporary directory for uploading (%s) is not writable, so import will fail' => 'La cartella temporanea di caricamento (%s) non &egrave; scrivibile, l\'importazione &egrave; fallita',
'Invalid Email' => 'Email non valida',
'Import cleared' => 'Importazione approvata',
'Continue' => 'Continua',
'Reset Import session' => 'Azzera la sessione di importazione',
'File is either too large or does not exist.' => 'Il file &egrave; troppo grande o non esiste.',
'No file was specified. Maybe the file is too big? ' => 'Nessun file specificato. Forse il file &egrave; troppo grande? ',
'File too big, please split it up into smaller ones' => 'File troppo grande, Dividilo in pi&ugrave; file di piccole dimensioni',
'Use of wrong characters in filename: ' => 'Utilizzati caratteri errati nel nome del file: ',
'Please choose whether to sign up immediately or to send a notification' => 'Si prega scegliere per la conferma immediata o per l\'invio di una notifica',
'Cannot read %s. file is not readable !' => 'Non si riesce a leggere %s. File non leggibile !',
'Something went wrong while uploading the file. Empty file received. Maybe the file is too big, or you have no permissions to read it.' => 'Qualcosa &egrave; andato storto durante il caricamento del file. Ricevuto un file vuoto. Pu&ograve; essere che il file sia troppo grande, o che tu non abbia il permesso di lettura.',
'Reading emails from file ... ' => 'Lettura email dal file... ',
'Error was around here &quot;%s&quot;' => 'Errore trovato qu&igrave; &quot;%s&quot;',
'Illegal character was %s' => 'Caratteri non validi in %s',
'A character has been found in the import which is not the delimiter indicated, but is likely to be confused for one. Please clean up your import file and try again' => 'Un carattere &egrave; stato trovato nell\'importazione che non &egrave; l\'indicatore di delimitazione, ma pu&ograve; essere confuso con uno di questi. Si prega ripulire il file di importazione e riprovare',
'ok, %d lines' => 'ok, %d linee',
'Cannot find column with email, please make sure the column is called &quot;email&quot; and not eg e-mail' => 'Non trovata una colonna con email, si prega controllare che la colonna sia intitolata &quot;email&quot; e non per esempio e-mail',
'Create new one' => 'Crea un nuovo',
'Skip Column' => 'Salta la colonna',
'Import Attributes' => 'Importa attributi',
'Continue' => 'Continua',
'Please identify the target of the following unknown columns' => 'Si prega identificare l\'obbiettivo per queste colonne sconosciute',
'Summary' => 'Sommario',
'maps to' => 'Mappa a',
'Create new Attribute' => 'Crea nuovo attributo',
'maps to' => 'Pianifica',
'Skip Column' => 'Salta la colonna',
'maps to' => 'Pianifica',
'%d lines will be imported' => '%d linee sono state importate',
'Confirm Import' => 'Conferma importazione',
'Test Output' => 'Verifica risultato',
'Record has no email' => 'I record non hanno email',
'Invalid Email' => 'Email non valide',
'clear value' => 'Pulisce valori',
'New Attribute' => 'Nuovo attributo',
'Skip value' => 'Salta valore',
'duplicate' => 'Duplicato',
'Duplicate Email' => 'Email duplicate',
' user imported as ' => ' Utente importato come ',
'duplicate' => 'duplicato',
'duplicate' => 'duplicato',
'Duplicate Email' => 'Email duplicato',
'All the emails already exist in the database and are member of the lists' => 'Tutte le emails esistono gi&agrave; nel database e sono membri delle liste',
'%s emails succesfully imported to the database and added to %d lists.' => '%s emails importate con successo nel database e aggiunte a %d liste.',
'%d emails subscribed to the lists' => '%d email sottoscritte alle liste',
'%s emails already existed in the database' => '%s email esistono gi&agrave; nel database',
'%d Invalid Emails found.' => '%d Trovate email non valide.',
'These records were added, but the email has been made up from ' => 'Questi records sono stati aggiunti, ma le email sono state preparate da ',
'These records were deleted. Check your source and reimport the data. Duplicates will be identified.' => 'Questi record erano cancellati. Controllate il vostro sorgente e reimporta i dati. I duplicati saranno identificati.',
'User data was updated for %d users' => 'I dati utente sono stati aggiornati per %d utenti',
'%d users were matched by foreign key, %d by email' => '%d utenti erano combinati tramite chiave sconosciuta, %d tramite email',
'phplist Import Results' => 'Risultati import phplist',
'Test output<br/>If the output looks ok, click %s to submit for real' => 'Verifica risultato<br/>Se i risultati sono validi, click %s su invia per renderli effettivi',
'Confirm Import' => 'Conferma importazione',
'Import some more emails' => 'Importa altre email',
'Adding users to list' => 'Aggiungi utenti alla lista',
'Select the lists to add the emails to' => 'Seleziona le liste a cui aggiungere le email',
'No lists available' => 'Nessuna lista disponibile',
'Add a list' => 'Aggiungi una lista',
'Select the groups to add the users to' => 'Seleziona il gruppo a cui aggiungere utenti',
'automatically added' => 'Automaticamente aggiunto',
 'The file you upload will need to have the attributes of the records on    the first line.     Make sure that the email column is called "email" and not something like "e-mail" or     "Email Address".     Case is not important.          If you have a column called "Foreign Key", this will be used for synchronisation between an     external database and the phpList database. The foreignkey will take precedence when matching     an existing subscriber. This will slow down the import process. If you use this, it is allowed to have     records without email, but an "Invalid Email" will be created instead. You can then do     a search on "invalid email" to find those records. Maximum size of a foreign key is 100.          Warning: the file needs to be plain text. Do not upload binary files like a Word Document.     ' => '<p>Il file che hai caricato deve avere gli attributi dei records nella prima riga. Controlla che la colonna email sia chiamata col nome "email" e non con nomi simili a "e-mail" o "Email Address". Maiuscolo o minuscolo non fa differenza.</p><p>Se hai una colonna chiamata "Foreign Key", Questa sar&agrave; usata per sincronizzarla tra un database esterno e il database PHPlist. La chiave "foreignkey" prender&agrave; la precedenza quando verificher&agrave; un utente esistente. Ciò rallenter&agrave; il processo di importazione. Se usate questo, &egrave; permesso avere records senza email, ma tuttavia “email non valida„ sar&agrave; generato. Potete allora fare una ricerca “email non valida„ per trovare questi records. La massima grandezza per "Foreign Key" &egrave; 100.</p><br/><br/><p><b>Attenzione</b>: L\'archivio deve essere di tipo testo semplice. Non caricare archivi binari come un Documento Word.</p><br/>',
'The following limits are set by your server: Maximum size of a total data sent to server: %s Maximum size of each individual file: %s' => 'I seguenti limiti sono definiti dal vostro server:<br/>
Massima grandezza dei dati totali inviati al server: <b>%s</b><br/>
Massima grandezza di ogni archivio individuale: <b>%s</b>
<br/>PHPlist non elabora archivi pi&ugrave; grandi di 1Mb',
'If you check "Test Output", you will get the list of parsed emails on screen, and the database will not be filled with the information. This is useful to find out whether the format of your file is correct. It will only show the first 50 records.' => 'Se scegli "Verifica risultato", otterai una lista a video delle emails analizzate, e il database non sar&agrave; riempito con nessuna informazione. Questo &egrave utile per trovare se il formato del vostro archivio &egrave; corretto. Verranno visualizzati solo i primi 50 records.',
'If you check "Show Warnings", you will get warnings for invalid records. Warnings will only be shown if you check "Test Output". They will be ignored when actually importing. ' => 'Se scegli "Visualizza avvertenze", verrai avvisato se records non validi. Le avvertenze verranno solo visualizzate se scelto anche "Verifica risultato". Verranno ignorate quando si esegue l\'importazione. ',
'If you check "Omit Invalid", invalid records will not be added. Invalid records are records without an email. Any other attributes will be added automatically, ie if the country of a record is not found, it will be added to the list of countries.' => 'Se scegli "Ometti non validi", i records non validi non verranno aggiunti. I records non validi sono i records senza email. Quansiasi altra attributo Any other attributes verr&agrave; aggiunto automaticamente, esempio se la nazione non &egrave; stata trovata nel record, verr&agrave; aggiunta dalla lista delle nazioni.',
'Assign Invalid will be used to create an email for subscribers with an invalid email address. You can use values between [ and ] to make up a value for the email. For example if your import file contains a column "First Name" and one called "Last Name", you can use "[first name] [last name]" to construct a new value for the email for this subscriber containing their first name and last name. The value [number] can be used to insert the sequence number for importing.' => 'Assegna non validi viene usato per creare una email per gli utenti con un indirizzo email non valido.
Puoi usare i valori fra [ e ] percomporre l\'email. Per esempio se il vostro archivio import contiene una colonna "First Name" e una colonna chiamata "Last Name", puoi usare 
"[first name] [last name]" per costruire un nuovo valore per l\'email per questo utente il suo nome e cognome.
Il valore [numero] puo essere usato il numero di sequenza per l\'importazione.',
'If you check "Overwrite Existing", information about a subscriber in the database will be replaced by the imported information. Subscribers are matched by email or foreign key.' => 'Se scegli "Sovrascrivi Esistenti", le informazioni relative all\'utente nel database saranno sostituire dalle informazioni importate. Gli utenti sono riferiti tramite email o chiave straniera (foreign key).',
'If you check "Retain Old Email", a conflict of two emails being the same will keep the old one and add "duplicate" to the new one. If you don&quot;t check it, the old one will get "duplicate" and the new one will take precedence.' => 'Se scegli "conserva vecchia email utente", vi &egrave; un conflitto tra le due emails essendo conservata la vecchia e aggiunto "duplicato" la nuova. Se non lo selezionate, il vecchio verr&agrave; "duplicate" e il nuovo prender_&agrave; la precedenza.',
'If you choose "send notification email" the subscribers you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails.' => 'Se scegli "invia email di notifica" agli utenti che state aggiungendo sara inviata la richiesta per la conferma della sottoscrizione a cui dovranno rispondere. Ci&ograve; &egrave; raccomandato, perch&eacuta; identificher&agrave; le email non valide.',
'phplist Import  Results' => 'phplist Import  Risultati',
'File containing emails' => 'Archivio contenente emails',
'Field Delimiter' => 'Delimitatore di Campo',
'(default is TAB)' => '(prefedinito &egrave; TAB)',
'Record Delimiter' => 'Delimitatore di Record',
'(default is line break)' => '(prefedinito &egrave; interruzione di linea)',
'Test output' => 'Verifica risultato',
'Show Warnings' => 'Visualizza Avvertenze',
'Omit Invalid' => 'Omette Non Validi',
'Assign Invalid' => 'Assegna Non Validi',
'Overwrite Existing' => 'Sovrascrive Esistenti',
'Retain Old User Email' => 'Conserva Email Utente Vecchia',
'Send&nbsp;Notification&nbsp;email' => 'Invia&nbsp;&nbsp;email&nbsp;di&nbsp;notifica',
'Make confirmed immediately' => 'Conferma immediatamente',
'Import' => 'Importa',
);
?>