<?php
## notes to translators:
# do not translate anything in square brackets: eg [RSS]
$lan = array (
 'noaccess' => 'Nessun messaggio, o non hai accesso a questo messaggio',
 'Warning: You indicated the content was not HTML, but there were  some HTML  tags in it. This  may  cause  errors' => 'Attenzione: hai indicato il contenuto come non html, ma c\'era dentro qualche tag html. Questo pu&ograve; causare errori',
 'Adding' => 'Aggiunta',
 'Mime Type is longer than 255 characters, this is trouble' => 'Tipo Mime &egrave; pi&ugrave; lungo di 255 caratteri, questo &egrave; un problema',
 'Added attachment ' => 'Allegato aggiunto',
 'Uploaded file not properly received, empty file' => 'File caricato non ricevuto correttamente, il file &egrave; vuoto',
 'Message saved' => 'Messaggio salvato',
 'Message added' => 'Messaggio aggiunto',
 'Message queued for send' => 'Messaggio accodato per l\'invio',
 'processqueue' => 'Elabora la coda messaggi',
 'Sorry, you used invalid characters in the Subject field.' => 'Spiacente,  hai usato caratteri non validi nel campo Oggetto.',
 'Sorry, you used invalid characters in the From field.' => 'Spiacente,  hai usato caratteri non validi nel campo Da',
 'Please enter a from line.' => 'Per favore inserisci la linea da',
 'Please enter a message' => 'Per favore inserisci un messaggio',
 'Please enter a subject' => 'Per favore inserisci un oggetto',
 'Error: you can use an attribute in one rule only' => 'Errore: puoi usare un attributo per una regola solamente.',
 'Please select the list(s) to send the campaign to' => 'Per favore scegli  la(e) lista(e) a cui mandare il messaggio',
 'No target email addresses listed for testing.' => 'Nessun indirizzo di destinazione elencato per la prova',
 'Email address not found to send test message.' => 'Indirizzo email per l\'invio della prova non trovato ',
 'Sent test mail to' => 'Invia l\'email di prova a',
 'Removed Attachment ' => 'Allegato rimosso',
 'Existing criteria' => 'criteri esistenti',
 'Remove' => 'rimuovi',
 'Calculating' => 'calcolo in corso',
 'Calculate' => 'calcolati',
 'Content' => 'Contenuto',
 'Attach' => 'allega',
 'Format' => 'Formato',
 'Scheduling' => 'Programmazione',
 'Criteria' => 'Criteri',
 'lists' => 'Liste',
 'Warning, You have unsaved changes
Click OK to continue, or Cancel to stay on this page
so you can save the changes.' => 'Attenzione, non hai salvato\\nClicca OK per continuare o Annulla per stare in questa pagina\\n in modo che puoi salvare i cambiamenti.',
 'What is prepare a message' => 'Cos\'&egrave; preparare un messaggio',
 'subject' => 'oggetto',
 'From Line' => 'Linea Da',
 'Embargoed Until' => 'Non inviabile (embargo) fino a',
 'Repeat campaign every' => 'Ripeti il messaggio ogni',
 'no repetition' => 'nessuna ripetizione',
 'Hour' => 'Ora',
 'Day' => 'Giorno',
 'Week' => 'Settimana',
 'Repeat Until' => 'Ripeti fino',
 'Auto Detect' => 'Auto rileva',
 'Send As' => 'Invia come',
 'html' => 'HTML',
 'text' => 'testo',
 'PDF' => 'PDF',
//  'text and html' => 'Text and HTML', //obsolete by bug 0009687
 'Text and PDF' => 'Testo e PDF',
 'Use Template' => 'Usa modello',
 'select one' => 'scegli uno',
  'If you want to use this message as the template for sending RSS feeds     select the frequency it should be used for and use [RSS] in your message to indicate where the list of items needs to go.' => 'If you want to use this message as the template for sending RSS feeds
    select the frequency it should be used for and use [RSS] in your message to indicate where the list of items needs to go.',
 'none' => 'nessuno',
 'message' => 'Messaggio',
 'expand' => 'espandi',
 'Plain text version of message' => 'Versione del messaggio in formato testo ',
 'Footer' => 'Pedice del messaggio (footer)',
 'Use [UNSUBSCRIBE] to insert the personal unsubscribe URL for each user.   Use [PREFERENCES] to insert the personal URL for a user to update their details.' => 'Usa <b>[UNSUBSCRIBE]</b> per inserire l\'indirizzo URL personale di disiscrizione per ogni utente.
   <br/>Usa <b>[PREFERENCES]</b> per inserire l\'indirizzo URL personale per permettere a ogni utente di cambiare le proprie preferenze.',
 'Add attachments to your campaign' => 'Aggiungi allegati al tuo messaggio',
 'The upload has the following limits set by the server' => 'Il caricamento ha i seguenti limiti impostati dal server',
 'Maximum size of total data being sent to the server' => 'Quantit&agrave; massima di dati da inviare al server',
 'Maximum size of each individual file' => 'Grandezza massima per ogni singolo file',
 'Current Attachments' => 'Allegati correnti',
 'filename' => 'nome del file',
 'desc' => 'descr',
 'size' => 'grandezza',
 'file' => 'file',
 'del' => 'canc',
 'New Attachment' => 'Nuovo allegato',
 'Add (and save)' => 'Aggiungi (e salva)',
 'Path to file on server' => 'Percorso del file sul server',
 'Description of attachment' => 'Descrizione dell\'allegato',
 'Delete Checked' => 'Cancellazione segnata',
 'Send Test Message' => 'Invia messaggio di prova',
 ' to email address(es)' => ' all\'indirizzo(i) email',
 '(comma separated addresses - all must be users)' => '(indirizzi separati da virgola - tutti devono essere utenti registrati)',
 '         Select the criteria for this message:                  to use a criteria, check the box next to it         then check the radio button next to the attribute you want to use         then choose the values of the attributes you want to send the message to         Note: Messages will be sent to people who fit to Criteria 1 AND Criteria 2 etc                   ' => '        <p><b>scegli i criteri per questo messaggio:</b>
       <ol>
       <li>per usare un criterio, controlla il box vicino ad esso
       <li>quindi spunta il bottone radio vicino all\'attributo che vuoi usare
       <li>quindi scegli i valori degli attributi a cui vuoi inviare il messaggio
       <i>Nota:</i> i messaggi verranno inviati alle persone che rispondono a  <i>Criterio 1</i> <b>E</b> <i>Criterio 2</i> ecc.
       </ol>
       ',
 'Criterion' => 'Criterio',
 'Use this one' => 'Usa questo',
 'or' => 'o',
 'is' => '&egrave;',
 'isnot' => 'non &egrave;',
 'isbefore' => '&egrave; prima',
 'isafter' => '&egrave; dopo',
 'There are currently no attributes available to use for sending. The campaign will go to any user on the lists selected' => 'Al momento non ci sono attributi disponibili da usare per l\'invio di un messaggio. Il messaggio andr&agrave; a qualsiasi utente della lista(e) scelta(e)',
 'checked' => 'Segnato ',
 'unchecked' => 'non segnato',
 'buggywithie' => 'Attenzione, questa funzionalit&agrave; &egrave; difettosa e inaffidabile con IE (Internet Explorer).\\nSarebbe meglio usare Mozilla, Firefox o Opera\\nAlternativamente disattiva STACKED_ATTRIBUTE_SELECTION nel tuo file di configurazione.',
 'matchallrules' => 'Trova corrispondenze con tutte queste regole',
 'matchanyrules' => 'Trova corrispondenze con qualsisi regola',
 'addcriterion' => 'Aggiungi una prova di verifica',
 'Save as Draft' => 'Salva i messaggi come bozza',
 'savechanges' => 'Salva cambiamenti',
 'selectattribute' => 'scegli attributo',
 'dd-mm-yyyy' => 'dd-mm-yyyy', # it's essential that the format is the same (ie dd-mm-yyyy)
  # above is all from send_core
 'Please select the lists you want to send it to' => 'Prego scegli le liste a cui vuoi mandarlo',
 'alllists' => 'Tutte le liste',
 'listactive' => 'La lista &egrave; attiva',
 'listnotactive' => 'La lista NON &egrave; attiva',
 'Select the lists to be excluded.' => 'scegli le liste da escludere',
 'The campaign will go to users who are a member of the lists above,     unless they are a member of one of the lists you select here.' => 'Il messaggio andr&agrave; agli utenti che sono membri delle liste sopra, a meno che non siano membri di una delle liste che hai scelto qui.',
 'Sorry, there are currently no lists available' => 'Spiacente, non ci sono liste disponibili al momento.',
 'Send Campaign' => 'Manda il messaggio alle liste selezionate',
 'You are trying to send a remote URL, but PEAR::HTTP_Request is not available, so this will fail' => 'Stai provando a inviare un URL remoto, ma PEAR::HTTP/Request non &egrave; disponibile, quindi l\'invio fallir&abrave;',
  ### new in 2.9.5
 'Misc' => 'Varie',
 'email to alert when sending of this message starts' => 'email da avvertire quando l\'invio di questo messaggio comincia:',
 'email to alert when sending of this message has finished' => 'email da avvertire quando l\'invio di questo messaggio &egrave; finito:',
 'separate multiple with a comma' => '(separa pi&ugrave; email con una virgola)',
 'operator' => 'operatore',
 'values' => 'valori',
 '%d users apply' => 'ci sono %d utenti ',
  # new in 2.10.1
  'reload' => 'ricarica',
  ## forgotten 
  'All Active Lists' => 'Tutte le liste attive',
);
?>
