<?php
$lan = array(
'Delete will delete user and all listmemberships' => 'Elimina, canceller&agrave; l\'utente e tutte le sue iscrizioni',
'No Lists' => 'nessuna lista',
'update page' => 'aggiorna pagina',
'unsubscribe page' => 'pagina di cancellazione',
'History' => 'Storico',
'User Details' => 'Dettagli utente',
'you only have privileges to view this page, not change any of the information' => 'Hai solo i privilegi per vedere questa pagina, non puoi modificare nessuna informazione',
'Delete will delete user from the list' => 'Elimina, canceller&agrave; l\'utente dall\'iscrizione alla/e liste',
'User added to group' => 'Utente aggiunto al gruppo',
'User added to list %s' => 'Utente aggiunto alla lista %s',
'Changes saved' => 'Modiche salvate',
'Deleting' => 'In cancellazione',
'Done' => 'Fatto',
'No such User' => 'Nessun utente',
'Add a new User' => 'Aggiungi un nuovo utente',
'encrypted' => 'crittografato',
'Save Changes' => 'Salva modifiche',
'User is blacklisted. No emails will be sent to this user' => 'L\'utente è nella blacklist. Non verr&agrave; inviata nessuna email a questo utente',
'Mailinglist Membership' => 'Rendi membro delle seguenti mailinglist',
'Group Membership' => 'Rendi membro dei seguenti gruppi',
'Please select the groups this user is a member of' => 'Seleziona i gruppi a cui appartiene questo utente',
# added 2.10.0
'ID' => 'ID',
'Email' => 'Email',
'Is this user confirmed' => '&Egrave; un utente confermato',
'Is this user blacklisted' => '&Egrave; in blacklist (0/1)',
'Number of bounces on this user' => 'Numero di email respinte di questo utente',
'Entered' => 'Inserito',
'Last Modified' => 'Ultima modifica',
'Unique ID for User' => 'ID Unico per questo utente',
'Send this user HTML emails' => 'Invia email in HTML a questo utente',
'Which page was used to subscribe' => 'Quale pagina &egrave; stata usata per l\'iscrizione',
'RSS Frequency' => 'Frequenza RSS',
'Last time password was changed' => 'L\'ultima volta che &egrave; stata modificata la password',
'Is this account disabled?' => 'Account disabilitato (0/1)',
'Additional data' => 'Dati addizionali',
'Foreign Key' => 'Chiave straniera',
'Error adding user, please check that the user exists' => 'Errore aggiungendo l\'utente, controllare che l\'utente non esista gi&agrave;',
);
?>
