<?php
$lan = array(
 'Delete will delete user and all listmemberships' => 'Cancella eliminer&agrave; l\'utente e tutte le sue iscrizioni alle liste',
 '%s users apply' => 'corrispondono %s utenti',
 'Users marked <font color=red>red</font> are unconfirmed' => 'Gli utenti segnati in <font color=red>rosso</font> sono "non confermati"',
 'Show only unconfirmed users' => 'Mostra solo utenti non confermati (conf)',
 'Show only blacklisted users' => 'Mostra solo utenti in blacklist (bl)',
 'email' => 'email',
 'bouncecount' => 'conteggio respinti',
 'entered' => 'inserito',
 'modified' => 'modificato',
 'foreignkey' => 'chiave esterna',
 'Sort by' => 'ordinato per',
 'desc' => 'disc',
 'asc' => 'asc',
 'Go' => 'Vai',
 'Find a user' => 'Trova un utente',
 'Email' => 'Email',
 'Foreign Key' => 'Chiave esterna',
 'reset' => 'reimposta',
 'Download all users as CSV file' => 'Scarica tutti gli utenti in un file CSV',
 'Add a User' => 'Aggiungi un utente',
 'confirmed' => 'conf.',
 'bl l' => 'bl',
 'del' => 'canc',
 'key' => 'chiave',
 'msgs' => 'mess.gi',
 'rss' => 'rss',
 'rss freq' => 'freq rss',
 'bncs' => 'rsp',
 'No users apply' => 'Nessun utente corrisponde',
 'Your privileges for this page are insufficient' => 'I tuoi permessi per questa pagina sono insufficienti',
 'Delete will delete user from the list' => 'Cancella canceller&agrave; l\'utente dalla lista',
 'deleting' => 'cancellazione',
 'Done' => 'Fatto',
 'User added' => 'Utente aggiunto',
 'Add this user' => 'Aggiungi questo utente',
 'Click on a link to use the corresponding public subscribe page to add this user:' => 'Clicca su un collegamento per usare la pagina di iscrizione per aggiungere l\'utente:',
 'Click this link to use the public subscribe page to add this user:' => 'Clicca sul collegamento per usare la pagina di iscrizione corrispondente per aggiungere questo utente:',
 'Listing user %d to %d' => 'Elenco utenti da %d a %d',
 'last sent' => 'ultimo inviato',
 '%s users in total' => '%s utenti in totale', // aggiunto, mancava
);
?>
