<?php

# file with common texts for translation

$lan = array(
  'Logout' => 'ログアウト',
  'Main Page' => 'メインページ',
  'Subscriber' => 'ユーザ',
  'Error' => 'エラー',
  'version' => 'バージョン',
  'powered by' => 'powered by',
  'Fatal Error' => '致命的なエラー',
  'Warning' => '警告',
  'Information' => 'インフォメーション',
  'help' => 'ヘルプ',
  'about' => 'アバウト',
  'lists' => 'リスト',
  'send a message' => 'メッセージ送信',
  'Subscribers' => 'ユーザ',
  'manage users' => 'ユーザ管理',
  'Campaigns' => 'メッセージ',
  'statistics' => '統計',
  'process queue' => 'キューの処理',
  'configure' => '設定',
  'Subscribe Pages' => '購読ページ',
  'Send a prepared message' => '準備済メッセージの送信',
  'Prepare a message' => 'メッセージの準備',
  'Templates' => 'テンプレート',
  'View Bounces' => 'バウンスの閲覧',
  'Process Bounces' => 'バウンスの処理',
  'Eventlog' => 'イベントログ',
  'Sunday' => 'Sunday',
  'Monday' => 'Monday',
  'Tuesday' => 'Tuesday',
  'Wednesday' => 'Wednesday',
  'Thursday' => 'Thursday',
  'Friday' => 'Friday',
  'Saturday' => 'Saturday',
  'January' => 'January',
  'February' => 'February',
  'March' => 'March',
  'April' => 'April',
  'May' => 'May',
  'June' => 'June',
  'July' => 'July',
  'August' => 'August',
  'September' => 'September',
  'October' => 'October',
  'November' => 'November',
  'December' => 'December',
  'Jan' => 'Jan',
  'Feb' => 'Feb',
  'Mar' => 'Mar',
  'Apr' => 'Apr',
  'May' => 'May',
  'Jun' => 'Jun',
  'Jul' => 'Jul',
  'Aug' => 'Aug',
  'Sep' => 'Sep',
  'Oct' => 'Oct',
  'Nov' => 'Nov',
  'Dec' => 'Dec',
  # from sendemaillib
  'Sending text only to' => '次にのみテキストメッセージを送信中：',
  'Sending Campaign' => 'メッセージ送信中',
  'with subject' => 'メールタイトルつき',
  'to' => 'to',
  'Admin Authentication initialisation failure' => '管理者認証の初期化失敗',
  'Your password for phplist' => 'phplistに対するあなたのパスワード',
  'Your password is' => 'Your password is',
  'Your password has been sent by email' => 'あなたのパスワードは電子メールで送信されました。',
  'Unable to send the password' => 'パスワードを送信することができません。',
  'Your IP address has changed. For security reasons, please login again' => 'あなたのIPアドレスが変更されました。セキュリティーの理由のためですので、再度ログインしてください。',
  'goodbye' => 'お疲れ様でした。',
  'good morning' => 'おはようございます。',
  'good afternoon' => 'こんにちは。',
  'good evening' => 'こんばんは。',
  'In safe mode, not everything will work as expected' => 'セーフモードではすべてが期待通りに機能するわけではありません。',
  'Things will work better when PHP magic_quotes_gpc = on' => 'PHP magic_quotes_gpc = <b>on</b> のときよく機能します。',
  'Things will work better when PHP magic_quotes_runtime = off' => 'PHP magic_quotes_runtime = off のときよく機能します。',
  'You are trying to use RSS, but XML is not included in your PHP' => 'あなたはRSSを使うことを試していますが、XMLがあなたのPHPにインクルードされていません。',
  'open_basedir restrictions are in effect, which may be the cause of the next warning' => 'open_basedir restrictions が実行されています。このことは次の警告の原因になるかもしれません。',
  'The attachment repository does not exist or is not writable' => '添付ファイルの置き場所が存在しません。または書き込み可能ではありません。',
  'You are trying to use PDF support without having FPDF loaded' => 'あなたはFPDFをロードすることなしにPDFサポートを使うことを試しています。',
  'The pageroot in your config does not match the current locationCheck your config file.' => 'あなたの設定のページルートは、現在のロケーションとマッチしません。<br />設定ファイルをチェックしてください。',
  'Sorry this page was not found in the plugin' => 'すいません。このページはプラグインにみつかりませんでした。',
  'Sorry not Implemented yet' => 'すいません。まだ導入されていません。',
  'You do not have enough privileges to access this page' => 'あなたはこのページにアクセスする十分な権限を持っていません。',
  'Sorry, help for this topic is not available yet: ' => 'すいません、このトピックのヘルプはまだ利用できません。: ',
  'Close this window' => 'このウィンドウを閉じる',
  'success' => '成功',
  'failed' => '失敗',
  'default login is' => 'Default login is',
  'with password' => 'with password',
  'Name' => '名前',
  'Password' => 'パスワード',
  'Enter' => 'ログイン',
  'forgot password' => 'パスワードを忘れた方へ',
  'enter your email' => '電子メールアドレスを入力',
  'send password' => 'パスワード送信',
  'An image exists on the server, check this box to keep the existing one' => 'サーバにイメージが存在します。存在するイメージを保存するためにこのボックスをチェックしてください。',
  'View Image' => 'イメージをみる',
  'Upload new image' => '新規イメージのアップロード',
  'textline' => 'テキストライン',
  'textarea' => 'テキストエリア',
  'date' => '日付',
  'checkbox' => 'チェックボックス',
  'radio' => 'ラジオボタン',
  'select' => '選択',
  'checkboxgroup' => 'チェックボックスグループ',
  'unnamed list' => '名前がつけられていないリスト',
  'Unknown' => 'Unknown',
  'very little time' => 'very little time',
  'A process for this page is already running and it was still alive' => 'このページのプロセスはすでに実行されていて、まだ生きています。',
  'seconds ago' => 'seconds ago',
  'We have been waiting too long, I guess the other process is still going ok' => '長時間待ち続けています。他のプロセスがまだ実行されていると推測されます。',
  'Sleeping for 20 seconds, aborting will quit' => 'Sleeping for 20 seconds, aborting will quit',
  'No Image was found' => 'イメージがみつかりませんでした。',
  'Campaigns' => 'メッセージ',
  'Bounces' => 'バウンス',
  'bounce' => 'バウンス',
  'msg' => 'msg', # as in short for message
  'time' => 'time',
  'sent' => 'sent',
  'text' => 'text',
  'html' => 'html',
  #
  # new for 2.9.5
  'delete user' => 'ユーザを削除',
  'unconfirm user' => 'ユーザを unconfirm',
  'delete user and bounce' => 'ユーザとバウンスを削除',
  'unconfirm user and delete bounce' => 'ユーザを unconfirm ・バウンスを削除',
  'blacklist user and delete bounce' => 'ユーザを購読解除済リストに追加・バウンスを削除',
  'delete bounce' => 'バウンスを削除',
  'blacklist user' => 'ユーザを購読解除済リストに追加',
  'manage bounces' => 'バウンスの管理',
  '%' => '%',
  'invalid login from %s, tried logging in as %s' => '%s からの不正なログインです。%s としてログインすることを試みました。',
  'successful password request from %s for %s' => 'successful password request from %s for %s',
  'failed password request from %s for %s' => 'failed password request from %s for %s',
  'login ip invalid from %s for %s (was %s)' => 'login ip invalid from %s for %s (was %s)',
  'invalidated login from %s for %s (error %s)' => 'invalidated login from %s for %s (error %s)',
  'close' => '閉じる',
  'open' => '開く',
  'import is not available' => 'インポートは利用できません。',

  # new for 2.10.0
  'Please wait, upgrading your database, do not interrupt' => 'お待ちください。あなたのデータベースをアップグレード中です。中断してはいけません。',
  'purgerss' => 'RSS消去',
  'Purge RSS items' => 'RSSアイテムの消去',
  'In order to login, you need to enable cookies in your browser' => 'ログインするために、あなたのブラウザのcookieを有効にする必要があります。',

  # added 2.10.2
  'Your version of PHP has a major security issue.It is best to upgrade to the latest version of PHP. Read More about this issue.' => 'あなたのPHPのバージョンは大きなセキュリティーの問題があります。 <br/>PHPの最新バージョンにアップグレードするのがベストです。この問題については<a href="http://www.hardened-php.net/globals-problem">ここ</a>を読んでください。',

);

?>
