<?php 
$lan = array(

  'add_list' => 'リストの追加', //duplicated in import1_text
  'cannot connect to remote database' => 'リモートデータベースに接続できません。',
  'No users to copy, is the prefix correct?' => 'ユーザは何もコピーされません、プレフィックスは正しいですか？',
  'Please enter details of the remote Server' => 'リモートサーバの詳細を入力してください。',
  'Server:' => 'サーバ:',
  'user' => 'ユーザ:',
  'Password:' => 'パスワード:',
  'Database Name:' => 'データベース名:',
  'Table prefix:' => 'テーブルプレフィックス:',
  'Usertable prefix:' => 'ユーザテーブルプレフィックス:',
  'select_lists' => '電子メールを追加するリストを選択',
  'Copy lists from remote server (lists are matched by name)' => 'リモートサーバからリストをコピー（リストは名前でマッチされます）',
  'Mark new users as HTML:' => '「HTMLメールを受信する」として新規ユーザをマーク:',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'もし"既存を上書き"をチェックするのでしたら、データベース内のユーザの情報は、インポートされた情報で置換されます。ユーザは電子メールアドレスでマッチされます。',
  'Overwrite Existing:' => '既存を上書き:',
  'Making connection with remote database' => 'リモートデータベースに接続中',
  'Getting data from ' => 'データを取得中 from ',
  'Remote version is' => 'リモートバージョン：',
  'Remote version has' => 'Remote version has',
  'users' => 'ユーザ',
  'lists' => 'リスト',
  'Copying lists' => 'リストをコピー中',
  'list' => 'リスト',
  'exists locally' => 'ローカルに存在します。',
  'created locally' => 'ローカルに作成されました。',
  'Remote list' => 'リモートリスト',
  'not created' => '作成されませんでした。',
  'Copying attributes' => '属性をコピー中',
  'Attribute' => '属性',
  'Copying users' => 'ユーザをコピー中',
  'overwriting local data' => 'ローカルデータを上書き中',
  'keeping local data' => 'ローカルデータを保持中',
  'is a new user' => 'は新規のユーザです。',
  'Error, no mapped attribute for' => 'エラー、属性がマップされませんでした：',
  'Error, no local list defined for' => 'エラー、ローカルリストが定義されませんでした：',
  'No lists available' => '利用可能なリストはありません。',
  'Done' => '実行',
  'new users' => '新規ユーザ',
  'and' => 'and',
  'existing users' => '既存ユーザ',
  'continue' => '続ける',

);
?>