<?php
$lan = array (
  'Email is a system attribute' => 'Email是系统栏位',
  'Converting' => '转换中',
  'from' => '从',
  'to' => '到',
  'deleting' => '删除中',
  'Cannot delete attribute, it is being used by the following forms:' => '无法删除栏位，目前被下面表单使用：',
  'Warning, changing types of attributes can take a long time' => '注意，修改任何类型的栏位都可能需要等候一段时间',
  'Sorry, merging of checkbox groups is not implemented yet' => '抱歉，合併选取方块群组还没完成',
  'cannot merge just one attribute' => '无法只合併一个栏位',
  'Merging' => '合併中',
  'into' => '变成',
  'Can only merge attributes of the same type' => '只能够合併同样类型的栏位',
  'Existing attributes' => '已存在的栏位',
  'No Attributes have been defined yet' => '还没定义任何栏位',
  'Load data from' => '读取资料自',
  'predefined defaults' => '预设值',
  'Attribute' => '栏位',
  'used in' => '使用于',
  'forms' => '表单',
  'tag' => '标籤',
  'name' => '名称',
  'Type' => '类型',
  'Default Value' => '预设值',
  'Order of Listing' => '顺序',
  'Is this attribute required?' => '必填？',
  'textline' => '文字方块',
  'checkbox' => '核选方块',
  'checkboxgroup' => '核选方块群组',
  'radio' => '单选项目',
  'select' => '下拉选单',
  'hidden' => '隐藏项目',
  'textarea' => '多行文字',
  'date' => '日期',
  'savechanges' => '储存',
  'With TAGGED attributes' => '使用标示的栏位',
  'delete' => '删除',
  'Merge' => '合併',
  'Add new Attribute' => '新增栏位',

);
?>