<?php
$lan = array (
  'No such record' => '没有记录',
  'Back to the list of bounces' => '回到退信清单',
  'Not Found' => '找不到<br/>',
  'Added %s to bouncecount for subscriber %s' => '新增 %s 到 %s 的退信指数<br/>',
  'Could not add %s to bouncecount for subscriber %s' => '无法新增 %s 到 %s 的退信指数<br/>',
  'Made subscriber %s unconfirmed' => '让使用者 %s 状态变成未确认<br/>',
  'Made subscriber %s to receive text' => '让使用者 %s 订阅纯文字版本<br/>',
  'Deleted subscriber %s' => '删除使用者 %s<br/>',
  'Deleting bounce %s .. ' => '删除退信中 %s ..',
  '..Done, loading next bounce..' => '..完成，读取下一封退信..',
  'No such Record' => '没有这笔记录',
  'Possible Actions:' => '动作：',
  'For subscriber with email' => '给使用者信箱',
  'Increase bouncecount with' => '增加退信指数于',
  '(use negative numbers to decrease)' => '(使用负数来减少)',
  'Mark subscriber as unconfirmed' => '让使用者状态变成未确认',
  '(so you can resend the request for confirmation)' => '(接着您就可以重新发送确认信函)',
  'Set subscriber to receive text instead of HTML' => '设定使用者订阅纯文字版本',
  'Delete subscriber' => '删除使用者',
  'Delete this bounce and go to the next' => '删除这封退信并且读取下一封',
  'Do the above' => '执行',
  'Bounce Details:' => '退信细节：',
  'ID' => 'ID',
  'Date' => '日期',
  'Status' => '状态',
  'Comment' => '意见',
  'Header' => '页首',
  'Body' => '内容',
  'Regular Expression' => '样式比对',
  'Action' => '操作',
  'Memo for this rule' => '这个规则的备注',
  'Add new Rule' => '新增规则',
  'Create New Rule based on this bounce' => '以这封退信建立新规则',

);
?>