<?php
$lan = array (
  'add_list' => '新增電子報',
  'cannot connect to remote database' => '無法連結遠端資料庫',
  'No users to copy, is the prefix correct?' => '無法複製使用者，確定前置字元正確？',
  'Please enter details of the remote Server' => '請輸入遠端伺服器資訊',
  'Server:' => '伺服器：',
  'user' => '帳號：',
  'Password:' => '密碼：',
  'Database Name:' => '資料庫名稱：',
  'Table prefix:' => '資料表前置字元：',
  'Usertable prefix:' => '使用者資料表前置字元：',
  'select_lists' => '選擇新增 email 訂閱的電子報',
  'Copy lists from remote server (lists are matched by name)' => '從遠端伺服器複製電子報 (透過名稱比對)',
  'Mark new users as HTML:' => '新使用者訂閱 HTML格式：',
  'If you check "Overwrite Existing", information about a user in the database will be replaced by the imported information. Users are matched by email.' => '如果您勾選 "覆蓋現有的"，已經存在的資料會被新的資料取代。',
  'Overwrite Existing:' => '覆蓋現有的：',
  'Making connection with remote database' => '與遠端資料庫連線中',
  'Getting data from ' => '取得資料自',
  'Remote version is' => '遠端版本',
  'Remote version has' => '遠端版本有',
  'users' => '使用者',
  'lists' => '電子報',
  'Copying lists' => '複製電子報中',
  'list' => '電子報',
  'exists locally' => '本地端存在的',
  'created locally' => '本地端建立的',
  'Remote list' => '遠端電子報',
  'not created' => '沒有建立',
  'Copying attributes' => '複製欄位',
  'Attribute' => '欄位',
  'Copying users' => '複製使用者中',
  'overwriting local data' => '覆蓋本地端資料',
  'keeping local data' => '保留本地端資料',
  'is a new user' => '是新使用者',
  'Error, no mapped attribute for' => '錯誤，沒有對應的欄位',
  'Error, no local list defined for' => '錯誤，本地端電子報未定義',
  'No lists available' => '沒有電子報可以訂閱',
  'Done' => '完成',
  'new users' => '新使用者',
  'and' => '與',
  'existing users' => '已經存在的使用者',
  'continue' => '繼續',

);
?>