<?php

$lan = array(

'Import emails from IMAP folders' => 'Import emails from IMAP folders',
'personal' => 'personal',
'folder' => 'folder',
'can\'t connect' => 'can\'t connect',
'imap_getmailboxes failed' => 'imap_getmailboxes failed',
'Please enter details of the IMAP account' => 'Please enter details of the IMAP account',
'Select the headers fields to search' => 'Select the headers fields to search',
'Mark new users as HTML' => 'Mark new subscribers as HTML',
'If you check' => 'If you check',
'information about a user in the database will be replaced by the imported information. Users are matched by email.' => 'information about a subscriber in the database will be replaced by the imported information. Subscribers are matched by email.',
'Only use complete addresses' => 'Only use complete addresses',
'addresses that do not have a real name will be ignored. Otherwise all emails will be imported.' => 'addresses that do not have a real name will be ignored. Otherwise all emails will be imported.',
'If you choose' => 'If you choose',
'send notification email' => 'send notification email',
'the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails.' => 'the users you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails.',
'Send&nbsp;Notification&nbsp;email&nbsp;' => 'Send&nbsp;Notification&nbsp;email&nbsp;',
'There are two ways to add the names of the users,  either one attribute for the entire name or two attributes, one for first name and one for last name. If you use &quot;two attributes&quot;, the name will be split after the first space.' => 'There are two ways to add the names of the users,
 either one attribute for the entire name or two attributes, one for first name and one for last name.
If you use \'two attributes\', the name will be split after the first space.',
'Use one attribute for name' => 'Use one attribute for name',
'Use two attributes for the name' => 'Use two attributes for the name',
'Attribute one' => 'Attribute one',
'Create Attribute' => 'Create Attribute',
'Attribute two' => 'Attribute two',
'Cannot continue' => 'Cannot continue',
'folders and' => 'folders and',
'unique emails found' => 'unique emails found',
'All the emails already exist in the database and are members of the' => 'All the emails already exist in the database and are members of the',
'succesfully imported to the database and added to' => 'succesfully imported to the database and added to',
'subscribed to the' => 'subscribed to the',
'emails already existed in the database' => 'emails already existed in the database',
'Invalid Emails found.' => 'Invalid Emails found.',
'These records were added, but the email has been made up. You can find them by doing a search on' => 'These records were added, but the email has been made up. You can find them by doing a search on',
'No emails found' => 'No emails found',
'Server' => 'Server',
'Password' => 'Password',
'Process Selected Folders' => 'Process Selected Folders',
'email was' => 'email was',
);
?>
