<?php

$lan = array(

'The temporary directory for uploading is not writable, so import will fail' => 'The temporary directory for uploading is not writable, so import will fail',
'Please select at least one list' => 'Please select at least one list',
'File is either too large or does not exist.' => 'File is either too large or does not exist.',
'No file was specified. Maybe the file is too big?' => 'No file was specified. Maybe the file is too big?',
'File too big, please split it up into smaller ones' => 'File too big, please split it up into smaller ones',
'Use of wrong characters: ' => 'Use of wrong characters: ',
'Please choose whether to sign up immediately or to send a notification' => 'Please choose whether to sign up immediately or to send a notification',
'Cannot read file. It is not readable !' => 'Cannot read file. It is not readable !',
'Something went wrong while uploading the file. Empty file received. Maybe the file is too big, or you have no permissions to read it.' => 'Something went wrong while uploading the file. Empty file received. Maybe the file is too big, or you have no permissions to read it.',
'Some characters that are not valid have been found. These might be delimiters. Please check the file and select the right delimiter.' => 'Some characters that are not valid have been found. These might be delimiters. Please check the file and select the right delimiter.',
'Import of existing subscriber' => 'Import of existing subscriber',
'Import of new subscriber' => 'Import of new subscriber',
'No data changed' => 'No data changed',
'List subscriptions:' => 'List subscriptions:',
'Was subscribed to:' => 'Was subscribed to:',
'Is now subscribed to:' => 'Is now subscribed to:',
'Not subscribed to any lists' => 'Not subscribed to any lists',
'Import by ' => 'Import by ',
'new email was' => 'new email was',
'new emails were' => 'new emails were',
'email was' => 'email was',
'emails were' => 'emails were',
'Import some more emails' => 'Import some more emails',
'Test output:' => 'Test output:',
'There should only be ONE email per line.' => 'There should only be ONE email per line.',
'If the output looks ok, go' => 'If the output looks ok, go',
'back' => 'back',
' to resubmit for real' => ' to resubmit for real',
'emails existed in the database' => 'emails existed in the database',
'All the emails already exist in the database.' => 'All the emails already exist in the database.',
'succesfully imported to the database and added to' => 'succesfully imported to the database and added to',
'subscribed to the' => 'subscribed to the',
'No lists available, ' => 'No lists available, ',
'The file you upload will need to contain the emails you want to add to these lists. Anything after the email will be added as attribute "Info" of the Subscriber. You can specify the rest of the attributes of these subscribers below. Warning: the file needs to be plain text. Do not upload binary files like a Word Document.' => 'The file you upload will need to contain the emails you want to add to these lists. Anything after the email will be added as attribute "Info" of the Subscriber. You can specify the rest of the attributes of these subscribers below. <b>Warning</b>: the file needs to be plain text. Do not upload binary files like a Word Document.',
'File containing emails:' => 'File containing emails:',
'Field Delimiter:' => 'Field Delimiter:',
'(default is TAB)' => '(default is TAB)',
'Record Delimiter:' => 'Record Delimiter:',
'(default is line break)' => '(default is line break)',
'If you check "Test Output", you will get the list of parsed emails on screen, and the database will not be filled with the information. This is useful to find out whether the format of your file is correct. It will only show the first 50 records.' => 'If you check "Test Output", you will get the list of parsed emails on screen, and the database will not be filled with the information. This is useful to find out whether the format of your file is correct. It will only show the first 50 records.',
'If you choose "send notification email" the subscribers you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails.' => 'If you choose "send notification email" the subscribers you are adding will be sent the request for confirmation of subscription to which they will have to reply. This is recommended, because it will identify invalid emails.',
'Send Notification email' => 'Send Notification email',
'Make confirmed immediately' => 'Make confirmed immediately',
);
?>
