<?php

$lan = array(

'Reload required' => 'Reload required',
'It is safe to click your stop button now, report will be sent by email to' => 'It is safe to click your "stop" button now, report will be sent by email to',
'Your webserver is running in safe_mode. Please keep this window open. It may reload several times to make sure all messages are sent.' => 'Your webserver is running in "safe_mode". Please keep this window open. It may reload several times to make sure all messages are sent.',
'is an RSS feed for' => 'is an RSS feed for',
'looking for users who can be excluded from this mailing' => 'looking for users who can be excluded from this processqueue run',
'Unconfirmed user' => 'Unconfirmed user',
'waiting for' => 'waiting for',
'to make sure we don\'t exceed our limit of' => 'to make sure we don\'t exceed our limit of',
'messages in' => 'messages in',
'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.' => 'There have been more than 10 attempts to send to %s that have been blocked for domain throttling.',
'Introducing extra delay to decrease throttle failures' => 'Introducing extra delay to decrease throttle failures',
'%s is currently over throttle limit of %d per %d seconds' => '%s is currently over throttle limit of %d per %d seconds',
'Processing batch of ' => 'Processing batch of ',
  'Campaign started' => 'Campaign started',
  'phplist has started sending the campaign with subject %s' => 'phplist has started sending the campaign with subject %s',
  'to view the progress of this campaign, go to http://%s' => 'to view the progress of this campaign, go to http://%s',
  'sending will finish in %s' => 'sending will finish in %s',
  'mins' => 'mins',
  'secs' => 'secs',
  'sending of this campaign will finish in %s' => 'sending of this campaign will finish in %s',
  'Campaign reached sending limit' => 'Campaign reached sending limit',
  'Message Campaign finished' => 'Message Campaign finished',
  'phplist has finished sending the campaign with subject %s' => 'phplist has finished sending the campaign with subject %s',
  'to view the results of this campaign, go to http://%s' => 'to view the results of this campaign, go to http://%s',
  'days' => 'days',
  'hours' => 'hours',
  'Campaign sending timed out, is past date to process until' => 'Campaign sending timed out, is past date to process until',
  'Time now ' => 'Time now ',
  'queue processing time has exceeded max processing time ' => 'queue processing time has exceeded max processing time ',
);
?>