<?php

$lan = array(

'Bounce processing error' => 'Bounce processing error',
'Bounce Processing info' => 'Bounce Processing info',
'system message bounced, user marked unconfirmed' => 'system message bounced, user marked unconfirmed',
'Bounced system message' => 'Bounced system message',
'User marked unconfirmed' => 'User marked unconfirmed',
'View Bounce' => 'View Bounce',
'bounces to fetch from the mailbox' => 'bounces to fetch from the mailbox',
'bounces to process' => 'bounces to process',
'Running in test mode, not deleting messages from mailbox' => 'Running in test mode, not deleting messages from mailbox',
'Processed messages will be deleted from mailbox' => 'Processed messages will be deleted from mailbox',
'Bounce mechanism not properly configured' => 'Bounce mechanism not properly configured',
'bounce_protocol not supported' => 'bounce_protocol not supported',
'Identifying consecutive bounces' => 'Identifying consecutive bounces',
'has consecutive bounces' => 'has consecutive bounces',
'over threshold, user marked unconfirmed' => 'over threshold, user marked unconfirmed',
'Auto Unsubscribed' => 'Auto Unsubscribed',
'User auto unsubscribed for' => 'User auto unsubscribed for',
'consecutive bounces' => 'consecutive bounces',
'of' => 'of',
'users processed' => 'users processed',
'processing first' => 'processing first',
'Report:' => 'Report:',
'Below are users who have been marked unconfirmed. The number in [] is their userid, the number in () is the number of consecutive bounces' => 'Below are users who have been marked unconfirmed. The number in [] is their userid, the number in () is the number of consecutive bounces',
'Processing bounces based on active bounce rules' => 'Processing bounces based on active bounce rules',
'Auto Blacklisted' => 'Auto Blacklisted',
'User auto blacklisted for' => 'User auto blacklisted for',
'bounce rule' => 'bounce rule',
'system message bounced, but unknown user' => 'system message bounced, but unknown user',
'bounces processed by advanced processing' => 'bounces processed by advanced processing',
'bounces were not matched by advanced processing rules' => 'bounces were not matched by advanced processing rules',
'Report of advanced bounce processing:' => 'Report of advanced bounce processing:',
'Below are users who have been marked unconfirmed. The in () is the number of consecutive bounces.' => 'Below are users who have been marked unconfirmed. The in () is the number of consecutive bounces.',
);
?>