<?php

$lan = array(

'Warning: You indicated the content was not HTML, but there were  some HTML  tags in it. This  may  cause  errors' => 'Warning: You indicated the content was not HTML, but there were  some HTML  tags in it. This  may  cause  errors',
'Adding' => 'Adding',
'Mime Type is longer than 255 characters, this is trouble' => 'Mime Type is longer than 255 characters, this is trouble',
'Added attachment ' => 'Added attachment ',
'Uploaded file not properly received, empty file' => 'Uploaded file not properly received, empty file',
'Message saved' => 'Message saved',
'Message added' => 'Message added',
'Message queued for send' => 'Message queued for send',
'Sorry, you used invalid characters in the Subject field.' => 'Sorry, you used invalid characters in the Subject field.',
'Sorry, you used invalid characters in the From field.' => 'Sorry, you used invalid characters in the From field.',
'Please enter a from line.' => 'Please enter a from line.',
'Please enter a message' => 'Please enter a message',
'Please enter a subject' => 'Please enter a subject',
'Error: you can use an attribute in one rule only' => 'Error: you can use an attribute in one rule only',
'Please select the list(s) to send the campaign to' => 'Please select the list(s) to send the campaign to',
'No target email addresses listed for testing.' => 'No target email addresses listed for testing.',
'Email address not found to send test message.' => 'Email address not found to send test message.',
'Sent test mail to' => 'Sent test mail to',
'Removed Attachment ' => 'Removed Attachment ',
'Existing criteria' => 'Existing criteria',
'Remove' => 'Remove',
'Calculating' => 'Calculating',
'Calculate' => 'Calculate',
'Content' => 'Content',
'Format' => 'Format',
'Attach' => 'Attach',
'Scheduling' => 'Scheduling',
'Criteria' => 'Criteria',
'Warning, You have unsaved changes
Click OK to continue, or Cancel to stay on this page
so you can save the changes.' => 'Warning, You have unsaved changes\nClick OK to continue, or Cancel to stay on this page\nso you can save the changes.',
'What is prepare a message' => 'What is prepare a message',
'From Line' => 'From Line',
'Embargoed Until' => 'Embargoed Until',
'Repeat campaign every' => 'Repeat campaign every',
'no repetition' => 'no repetition',
'Hour' => 'Hour',
'Day' => 'Day',
'Week' => 'Week',
'Repeat Until' => 'Repeat Until',
'Auto Detect' => 'Auto Detect',
'Send As' => 'Send as',
'PDF' => 'PDF',
'Text and PDF' => 'Text and PDF',
'Use Template' => 'Use Template',
'select one' => 'select one',
'If you want to use this message as the template for sending RSS feeds     select the frequency it should be used for and use [RSS] in your message to indicate where the list of items needs to go.' => 'If you want to use this message as the template for sending RSS feeds
    select the frequency it should be used for and use [RSS] in your message to indicate where the list of items needs to go.',
'Plain text version of message' => 'Plain text version of message',
'Footer' => 'Footer',
'Use [UNSUBSCRIBE] to insert the personal unsubscribe URL for each user.' => 'Use <b>[UNSUBSCRIBE]</b> to insert the personal unsubscribe URL for each user.',
'Use [PREFERENCES] to insert the personal URL for a user to update their details.' => 'Use <b>[PREFERENCES]</b> to insert the personal URL for a user to update their details.',
'Use [FORWARD] to add a personalised URL to forward the message to someone else.' => 'Use <b>[FORWARD]</b> to add a personalised URL to forward the message to someone else.',
'Use [UNSUBSCRIBE] to insert the personal unsubscribe URL for each user.   Use [PREFERENCES] to insert the personal URL for a user to update their details.' => 'Use <b>[UNSUBSCRIBE]</b> to insert the personal unsubscribe URL for each user.
  <br/>Use <b>[PREFERENCES]</b> to insert the personal URL for a user to update their details.',
'Add attachments to your campaign' => 'Add attachments to your campaign',
'The upload has the following limits set by the server' => 'The upload has the following limits set by the server',
'Maximum size of total data being sent to the server' => 'Maximum size of total data being sent to the server',
'Maximum size of each individual file' => 'Maximum size of each individual file',
'Current Attachments' => 'Current Attachments',
'New Attachment' => 'New Attachment',
'Add (and save)' => 'Add (and save)',
'Path to file on server' => 'Path to file on server',
'Description of attachment' => 'Description of attachment',
'Delete Checked' => 'Delete Checked',
'Send Test Message' => 'Send Test Message',
' to email address(es)' => ' to email address(es)',
'(comma separated addresses - all must be users)' => '(comma separated addresses - all must be users)',
'         Select the criteria for this message:                  to use a criteria, check the box next to it         then check the radio button next to the attribute you want to use         then choose the values of the attributes you want to send the message to         Note: Messages will be sent to people who fit to Criteria 1 AND Criteria 2 etc                   ' => '
        <p class="information"><b>Select the criteria for this message:</b></p>
        <ol>
        <li>to use a criteria, check the box next to it</li>
        <li>then check the radio button next to the attribute you want to use</li>
        <li>then choose the values of the attributes you want to send the message to
        <i>Note:</i> Messages will be sent to people who fit to <i>Criteria 1</i> <b>AND</b> <i>Criteria 2</i> etc </li>
        </ol>
        ',
'Criterion' => 'Criterion',
'Use this one' => 'Use this one',
'There are currently no attributes available to use for sending. The campaign will go to any user on the lists selected' => 'There are currently no attributes available to use for sending. The campaign will go to any user on the lists selected',
'Save as Draft' => 'Save as draft',
'Please select the lists you want to send it to' => 'Please select the lists you want to send it to',
'Select the lists to be excluded.' => 'Select the lists to be excluded.',
'The campaign will go to users who are a member of the lists above,     unless they are a member of one of the lists you select here.' => 'The campaign will go to users who are a member of the lists above,
    unless they are a member of one of the lists you select here.',
'Sorry, there are currently no lists available' => 'Sorry, there are currently no lists available',
'Send Campaign' => 'Send campaign',
'You are trying to send a remote URL, but PEAR::HTTP_Request is not available, so this will fail' => 'You are trying to send a remote URL, but PEAR::HTTP/Request is not available, so this will fail',
'use [FORWARD] to add a personalised URL to forward the message to someone else.' => 'use <b>[FORWARD]</b> to add a personalised URL to forward the message to someone else.',
'PGP' => 'PGP',
'Sign message' => 'Sign message',
'Select email to sign with' => 'Select email to sign with',
'Enter pass phrase' => 'Enter pass phrase',
'Encrypt message' => 'Encrypt message',
'When a message cannot be encrypted because the public key cannot be found' => 'When a message cannot be encrypted because the public key cannot be found',
'Send it anyway, but unencrypted' => 'Send it anyway, but unencrypted',
'Do not send it' => 'Do not send it',
'No RSS' => 'No RSS',
'start a new message' => 'Start a new campaign',
'Choose an existing draft message to work on' => 'Choose an existing draft campaign to work on',
'add' => 'Add',
'Send your message from' => 'Send your message from',
'a URL (website)' => 'a URL (website)',
'Enter it here' => 'Enter it here',
'URL' => 'URL',
'Time is Based on the Server Time' => 'Time is Based on the Server Time',
'Current Server Time is' => 'Current Server Time is',
'requeue every' => 'Requeue every',
'do not requeue' => 'Do not requeue',
'add Google tracking code' => 'Add Google tracking code',
'Estimated size of mailout' => 'Estimated size of mailout',
'campaigns deleted' => 'Campaigns deleted',
'campaign deleted' => 'Campaign deleted',
'Draft messages' => 'Draft campaigns',
'Forward' => 'Forward',
'Misc' => 'Misc',
'RSS' => 'RSS',
'When a user forwards to a friend, the friend will receive this message instead of the one on the content tab.' => 'When a user forwards to a friend, the friend will receive this message instead of the one on the content tab.',
'forwardfooter' => 'forwardfooter',
'The footer of the forwarded message.' => 'The footer of the forwarded message.',
'email to alert when sending of this message starts' => 'email to alert when sending of this message starts',
'separate multiple with a comma' => 'separate multiple with a comma',
'email to alert when sending of this message has finished' => 'email to alert when sending of this message has finished',
'No emails capable of signing' => 'No emails capable of signing',
'You should not paste the results of a test email back into the editor' => 'You should not paste the results of a test email back into the editor',
'This will break the click track statistics.' => 'This will break the click track statistics.',
'requeue until' => 'Requeue until',
'subject missing' => 'Subject missing',
'message content missing' => 'Message content missing',
'destination lists missing' => 'Destination lists missing',
'filename' => 'Filename',
'size' => 'Size',
'file' => 'file',
'When a user forwards to a friend," .
  " the friend will receive this message instead of the one on the content tab.' => 'When a user forwards to a friend," .
  " the friend will receive this message instead of the one on the content tab.',
'text and html' => 'text and html',
'or' => 'or',
'Estimated size of HTML email' => 'Estimated size of HTML email',
'Estimated size of text email' => 'Estimated size of text email',
'About %d users to receive HTML and %s users to receive text version of email' => 'About %d users to receive HTML and %s users to receive text version of email',
'From missing' => 'From missing',
);
